namhee/nhee_boj11536.cpp

namhee / 8월 5주차 / 1문제

---

Yerin99/897. Increasing Order Search Tree.py

yerin park / 9월 0주차 / 1문제

---

lcy8047/hideandseek.cpp
lcy8047/remotecontroler.cpp

lcy8047 / 9월 1주차 / 2문제

---

lysuk96/BOJ_1085.py

Younsuk Lee / 9월 1주차 / 1문제

---

Dongyeon/17268.py
Dongyeon/1904.py
Dongyeon/1912.py
Dongyeon/9095.py

이 글을 보는 여러분 모두 좋은 결과 있으시길 바랍니다~~!

Dongyeon / 9월 1주차 / 4문제

---

Yerin99/P_A_C_K.py
Yerin99/R_P_S.py
Yerin99/로프.py
Yerin99/타_일_링.py

yerin park / 9월 2주차 / 4문제

---

kimdonghun/PGSDevlopingFunc.cpp
kimdonghun/[BOJ]PutBridge.cpp
kimdonghun/[PGS]Printer.cpp

KimDongHun / 9월 3주차 / 3문제

---

Yerin99/1065. 한수.py
Yerin99/9020. 골드바흐의 추측.py
Yerin99/로_보_캅.py

yerin park / 9월 3주차 / 3문제

---

seunggil/10816.cpp
seunggil/2609.cpp
seunggil/9095.cpp

seunggil / 9월 4주차 / 3문제

---

Yerin99/18258. 큐 2.py
Yerin99/8958. OX퀴즈.py
Yerin99/R_A_N_K.py

yerin park / 9월 4주차 / 3문제

---

kimdonghun/[BOJ]1076_Resistance.cpp
kimdonghun/[BOJ]1100_WhiteSquare.cpp
kimdonghun/[BOJ]1145_LeastMultiple.cpp

kimdonghun / 9월 5주차 / 3문제

---

gusah009/[BOJ]색종이만들기.cpp
gusah009/[BOJ]숨바꼭질3.cpp
gusah009/[BOJ]스티커.cpp
gusah009/[BOJ]치즈.cpp
gusah009/[PGS]_weekly8.cpp

gusah009 / 10월 1주차 / 5문제

---

Yerin99/1629. 곱셈.py
Yerin99/1912. 연속합.py
Yerin99/공_항.py

공항(AIRPORT)문제 쉬웠는데 입출력 문제 때문에 시간이 많이 들었다 ㅠ.ㅠ

Yerin Park / 10월 2주차 / 3문제

---

songmody/loop/2step_findN.java
songmody/loop/2step_perfectNum.java
songmody/loop/2step_sumofNum.java

songmody / 11월 1주차 / 3문제

---

Dongyeon/1012_유기농배추.py
Dongyeon/1016.py

Dongyeon / 11월 1주차 / 2문제

---

gwanghoon/boj1003.py
gwanghoon/boj_1260.py
gwanghoon/boj_1978.py

sorry for the late submission......

gwanghoon / 11월 2주차 / 3문제

---

Yerin99/11286. 절댓값 힙.py
Yerin99/1715. 카드 정렬하기.py
Yerin99/18222. 투에-모스 문자열.py

yerin park / 11월 4주차 / 3문제

---

namhee/nh046_boj02750.cpp

커밋에는 없지만 저번주 PR에 합쳐진 약수 찾기, 일곱 난쟁이, 그리고 커밋의 수 정렬하기 문제까지 해서 3문제입니다!

namhee / 12월 1주차 / 3문제

---

lcy8047/LJESNJAK.cpp
lcy8047/easyProblem.cpp
lcy8047/friend.cpp
lcy8047/groupWordChecker.cpp
lcy8047/josephus.cpp
lcy8047/sort.cpp

lcy8047 / 12월 3주차 / 6문제

---

Ernstjunger-1914/[BOJ]0 = not cute  1 = cute.cpp

https://www.acmicpc.net/problem/10886

Ernstjunger-1914 / 12월 4주차 / 6문제

---

yongjunleeme/2146.cpp

https://www.acmicpc.net/problem/2146

yongjunleeme / 12월 4주차 / 1문제

---

gusah009/[BOJ]01타일.cpp

https://www.acmicpc.net/problem/1904

gusah009 / 12월 4주차 / 1문제

---

lcy8047/BIJELE.cpp
lcy8047/R2.cpp
lcy8047/cardgame.cpp

lcy8047 / 12월 4주차 / 3문제

---

Jeonghak/2557_HelloWorld.cpp
JeonghakLee/2557HelloWorld.cpp

Jeonghak / 1월 1주차 / 1문제

---

shasuri/2557_HelloWorld.txt

태블릿으로 하려니까 어렵네요...
분류는 단순구현입니다.
무슨 언어로 풀었을까요?

shasuri / 1월 1주차 / 1문제

---

HyeGyoungPark/2557_helloworld.py

hello world 문제는 입력도 없고 출력을 한 줄만 하면 되니까 파이썬으로 하는 것이 다른 언어보다 더 좋을 것이라고 생각했습니다.
알고리즘 분류는 단순 구현 입니다.

HyeGyoungPark / 1월 1주차 / 1문제

---

c0np4nn4/1448.cpp
c0np4nn4/2557.cpp

c0np4nn4 / 1월 1주차 / 1문제

---

dmstj920/2557_hello_world.cpp

dmstj920 / 1월 1주차 / 1문제

---

SeongHyun/2557_helloworld.py

문자열을 출력하는 문제입니다.
알고리즘 분류는 단순 구현입니다.

seonghyun koo / 1월 1주차 / 1문제

---

kimdokyun/C++/boj_2557.cpp
kimdokyun/Python/boj_2557.py

kim dokyun / 1월 1주차 / 1문제

---

llddang/2257_HelloWorld.cpp

python은 print한 번 만 쓰면 되는데 cpp로 하려니까 main함수 만들고 해야하는게 귀찮은 것 같습니다
알고리즘 분류는 단순 구현입니다.

llddang / 1월 1주차 / 1문제

---

myeongseo/2557_helloworld.py

myeongseo / 1월 1주차 / 1문제

---

gusah009/[BOJ]파도반수열.cpp

https://www.acmicpc.net/problem/9461

gusah009 / 1월 1주차 / 1문제

---

seunggil/python/11052.py
seunggil/python/1904.py
seunggil/python/2491.py

seunggil / 1월 1주차 / 3문제

---

namhee/nh049_boj01476.cpp
namhee/nh050_boj01748.cpp
namhee/nh051_boj05565.cpp

namhee / 1월 1주차 / 3문제

---

thkang727/2557_helloworld.py

hello world문제는 OT 용 커밋 연습문제로, 쉬운 문제였습니다.
알고리즈 분류는 단순 구현입니다.

thkang727 / 1월1주차 / 1문제

---

junbo9/10808_최대최소.py
junbo9/2557_helloworld.py
junbo9/최소, 최대

hello world 는 출력의 함수와 정확히 적는거에서 실수했습니다
분류는 단순구현입니다

junbo9/1월 1주차 /1문제

---

Jeonghak/1012_유기농 배추.cpp
Jeonghak/1260_DFS와 BFS.cpp
Jeonghak/2178번_미로탐색.cpp

알고리즘 문제를 오랜만에 풀어서 감을 다시 잡는 데 시간이 좀 걸렸습니다.
3문제 중 미로탐색이 생각할 것이 좀 있었고 
3문제의 알고리즘 분류는 모두  DFS, BFS 입니다.

Jeonghak / 1월 2주차 / 3문제

---

SeongHyun/11279_maxheap.py
SeongHyun/1655_median.py
SeongHyun/2606_virus.py

바이러스 -> 정점 1 과 연결된 모든 정점을 깊이우선탐색하였습니다. 알고리즘 분류는 그래프, DFS입니다.
최대 힙 -> 0이 들어올때 최대 힙에서 뽑아낸 최댓값을 출력합니다. 알고리즘 분류는 우선순위 큐입니다.
가운데를 말해요-> 앞뒤로 최대 힙과 최소 힙을 만들어 중앙값을 출력합니다. 알고리즘 분류는 우선순위 큐입니다.

seonghyun koo / 1월 2주차 / 3문제

---

myeongseo/1002_터렛.cpp
myeongseo/1003_피보나치함수.cpp
myeongseo/1004_어린왕자.cpp

'터렛'은 중간 중간 문제를 잘못 이해하여 여러 번 다시 푸느라 생각보다 시간이 좀 걸렸습니다.
'피보나치 함수'는 시간 초과가 나서 시간을 줄이도록 노력했습니다.
'어린왕자'는 생각보다 빨리 풀이 아이디어가 떠올라서 쉽게 풀었습니다.

myeongseo / 1월 2주차 / 3문제

---

kimdokyun/C++/boj_1074.cpp
kimdokyun/C++/boj_1107.cpp
kimdokyun/C++/boj_1389.cpp
kimdokyun/Python/boj_1074.py
kimdokyun/Python/boj_1107.py
kimdokyun/Python/boj_1389.py

[1074 Z ] 재귀함수를 이용하여 해결하였습니다.
[1107 리모컨 ] 완전탐색으로 해결하였습니다.
[1389 케빈 베이컨의 6단계 법칙 ] 플로이드 와샬로 해결했습니다.

kimdokyun / 1월 2주차 / 3문제

---

HyeGyoungPark/11000_pqclass.cpp
HyeGyoungPark/11508_greedy2plusone.cpp
HyeGyoungPark/14494_DPbasic.cpp
HyeGyoungPark/2217_sortrope.cpp

알고리즘 분류는 DP, 정렬, 그리디 입니다.
강의실 배정 문제가 제일 어려웠습니다. 벡터만 써서 처음 접근했을 때 테케는 다 되는데 틀렸다하여 반례들을 찾는 것이 매우 오래걸렸는데 결국 계속 통과를 못하여 우선순위 큐를 사용했습니다. 우선순위 큐로 접근 방식을 생각하는 것도 오래걸렸습니다.
다이나믹이 뭐예요?는 자료형을 고려하지 않아서 30분동안 왜 다른 값이 나오는가 고민했습니다. 자료형의 중요성을 다시 깨달았습니다.

HyeGyoungPark / 1월 2주차 / 4문제

---

11399_ATM.py
11508_2+1세일.py
1965_상자넣기.c

[11508][11399]그리디 알고리즘 / [1965]동적 프로그래밍 문제를 풀었습니다.
[11508] 2+1세일 문제는 c언어로 풀다가 배열을 정렬하는 과정에서 시간 초과가 일어나서 파이썬으로 바꾸어 풀게 되었습니다. 
[1965] 상자넣기 문제는 어떤 식으로 구현할지 생각하는 것이 오래 걸렸습니다.

dmstj920 / 1월 2주차 / 3문제

---

thkang727/10773_제로.cpp
thkang727/16953_A->B.cpp
thkang727/2110_공유기 설치.cpp

단순구현/스택[10773], 그리디[16953], 이분탐색[2110] 에 대해 풀었습니다.
난이도 상으로는 이분탐색 문제였던 2110_공유기 설치 문제가 어려웠긴 했으나, 표기된 난이도 대비 체감은 A->B 문제가 생각보다 어려웠습니다. 뭔가 쉽게 풀릴 것 같은데 계속 막혔어서 조금 더 지연되었던 것 같습니다. 공유기 설치는 제가 골드문제를 잘 못푸는데, 생각보다 빨리 풀려서 신기했어요

thkang727/1월 2주차/ 3문제

---

llddang/ACMCraft.cpp
llddang/명령프롬프트.cpp
llddang/피보나치함수.cpp

llddang / 1월 2주차 / 3문제

---

junbo9/1000_adding.py
junbo9/4673_self number
junbo9/9074_add.phy

파이썬과 관련된 알고리즘을 하려고하였으나 실버를 풀고나보니 기본기가 부족한것같아서 출력과 함수에대해서 좀만 더하고 다시해보랴고합니다

junbo 9/1월 2주차 4문제

---

eodudrepublic/2557_HelloWorld.py

Hello World 문제에서 !를 출력을 안해서 틀렸었습니다.
알고리즘 분류는 단순 구현입니다.

eodudrepublic / 1월 1주차 / 1문제

---

llddang/1012_유기농배추.cpp
llddang/1024_수열의합.cpp
llddang/9020_골드바흐의추측.cpp

1012_유기농 배추
처음에 문제를 이해하지 못하여 이해하는데 시간이 걸렸고, 그 이후에는 (0,0)에서 x, y좌표를 -1, -1하면 인덱스 밖으로 나가는 것을 어떻게 깔끔하게 만들수있는지 고민한다고 시간 걸렸습니다.
알고리즘 분류 
그래프 이론, 그래프 탐색, 너비 우선 탐색, 깊이 우선 탐색
1024_수열의 합
다른 데서 어려움을 겪지 않았으나 문제에 100개 이상 넘어가면 -1로 출력하라는 문구를 보지 못하여서 틀린 이유를 찾는다고 시간이 걸렸습니다..
알고리즘 분류
수학
9020_골드바흐의 추측
어려움은 없었습니다!
알고리즘 분류
수학 정수론 소수 판정 에라토스테네스의 체

llddang / 1월 3주차 / 3문제

---

HyeGyoungPark/1012_DFScabbage.cpp
HyeGyoungPark/1049_guitarstring.cpp
HyeGyoungPark/1074_Z.cpp

[알고리즘 분류]
유기농 배추는 DFS/BFS, 그래프 탐색 입니다.
Z는 분할 정복, 재귀 입니다.
기타줄은 그리디, 수학 입니다.
유기농 배추의 경우 DFS를 구현하는 방법을 생각할 때 시간이 오래 걸렸고, 평소 int i 같이 많이 쓰이는 변수는 int라고 선언을 자주 해 주면 바이트를 잡아먹길래 (for(int i=0;) 같이 반복문 안에 선언하지 않고 밖에 한 번 선언해서 사용하는 방식을 선호했는데(밖에 int i; 한 뒤 for( i=0;) 으로 바로 작성) 그러니까 어딘가에서 꼬였는지 값이 달랐습니다. 그래서 그 부분에서 원인을 찾느라 시간이 오래 걸렸습니다.
Z는 처음에 공통점을 찾을 수 있으리라 생각해서 재귀로 접근하는데 시간이 오래 걸렸고, 재귀로 해결하지 못했습니다. 이후 분할 정복도 가능하다는 것을 보고(분류에 있었음) 분할 정복으로 접근하여 해결하였습니다.
기타줄은 계산 과정을 짤 때 6의 배수도 고려해야 한다는 것을 처음에 생각하지 못했습니다.

HyeGyoungPark / 1월 3주차 / 3문제

---

shasuri/3rd_week/12852_dp.cpp
shasuri/3rd_week/1697_bfs.cpp
shasuri/3rd_week/dx_class_test_1.cpp

각한 부분은 두번째 커밋에 적어놨습니다~
커밋내용 바꾸기 귀찮아서 새로 커밋한 저를 용서해주세요🙏🙏
코드리뷰는 가능한 내일 해보도록 하겠습니다!
삼성 특강 테스트 쳐봤는데... 벽이 너무높았습니다... 한문제도 제대로 못풀었네요😂😂

shasuri / 1월 3주차 / 3문제

---

dmstj920/10773_제로.cpp
dmstj920/1655_가운데를말해요.cpp
dmstj920/1764_듣보잡.cpp

알고리즘 분류 : [10773] 구현, 자료구조,  스택 / [1655] 우선순위 큐 / [1764] 문자열, 정렬
[1073] c++로 문제를 푸는 것은 처음이라 쉬운 문제를 골라 풀어보았습니다.  
확실히 벡터를 이용하니 삽입과 삭제가 편하네요!
[1655] 우선순위 큐를 생각하지 못하고 벡터로 자꾸 풀다가 시간 초과가 많이 났습니다.  우선순위 큐로 바꾸어 풀어도 시간 초과가 나길래 다른 분들의 코드를 참고 해보니 ios_base::sync_with_stdio(false);와 cin.tie(NULL); 구문을 쓰면 시간이 더 절약 되는 것을 알았습니다.
[1764] 처음에 듣도 못한 사람들의 벡터와 보도 못한 사람들의 벡터를 따로 잡고 같은 게 있으면 다른 벡터에 넣어 그걸 출력했었는데 시간 초과가 났습니다. 그래서 이진 탐색으로 공통적인 사람들을 찾아내니 시간 초과도 안나고 간편했습니다. 이진 탐색은 배열이 정렬이 되어있어야 하는데 이를 생각하지 못하다가 시간이 조금 더 걸렸습니다.  이론적으로만 알고 있는 알고리즘을 문제를 풀 때 더 활용해보아야겠다는 생각이 든 문제입니다!

dmstj920 / 1월 3주차 / 3문제

---

Ernstjunger-1914/[BOJ]Zadanie próbne 2.cpp
Ernstjunger-1914/[BOJ]부호.cpp
Ernstjunger-1914/[BOJ]서강그라운드.cpp
Ernstjunger-1914/[BOJ]테트로미노.cpp

저번처럼 골통이 깨지고 싶진 않아서 이번엔 쉬운 문제도 풀어보았습니다.

Ernstjunger-1914 / 1월 2주차 / 4문제

---

9095_1,2,3더하기/9095_1,2,3더하기.cpp
thkang727/1026_보물.cpp
thkang727/1463_1로 만들기.cpp

1026_보물(정렬,단순구현)문제이고, 1463_1로만들기(DP)문제, 9095_1,2,3더하기(DP)문제입니다.
1026문제의 경우 최소를 찾는 경우의 수를 생각하다가, 한 줄은 큰 순서로,
한 줄은 작은 순서로 두고 해보았습니다.
1435문제의 경우 처음에는 경우의 수 몇 가지를 계산해본 후 단순구현 해보았으나, 안되어서 나머지 경우를 계산하보고 DP로 풀이해습니다. 
DP관련 추가 문제풀이를 하고 싶어 9095문제를 풀었습니다. 연관성을 찾는데 엄청 애를 썻는데, 알고보니 1,2,3 에서 수 그대로를 하나의 경우의 수로 두지 않아서 헤맸었네요.
DP 관련 문제풀이에 익숙하지 않은것 같아 DP로 여러문제를 풀이해보려 합니다.

thkang727/ 1월 3주차 / 3문제

---

c0np4nn4/[BOJ] 1068_트리.cpp
c0np4nn4/[BOJ] 1120_문자열.cpp
c0np4nn4/[BOJ] 1302_베스트셀러.cpp
c0np4nn4/[BOJ] 1543_문서 검색.cpp

문서검색, 베스트셀러 : 문자열 문제를 연습하는 취지로 해결했습니다.
트리 : 2주차의 세그먼트 트리 문제에 이어 트리 문제를 연습하는 취지로 공부했습니다.

c0np4nn4 / 1월 3주차 / 3문제

---

namhee/nh052_boj10172.java
namhee/nh053_boj10171.java
namhee/nh054_boj02475.java

namhee / 1월 3주차 / 3문제

---

jaewon/11403_findPath.cpp
jaewon/11659_sumSection4.cpp
jaewon/12852_makeone2.cpp
jaewon/16236_babyshark.cpp
jaewon/16928_snakeLadderGame.cpp
jaewon/2239_sudoku.cpp
jaewon/2252_line.cpp
jaewon/2623_musicprogram.cpp

- 실버3 난이도로 책정 되어있지만 제 생각엔 브론즈3 ~ 브론즈1 정도 인 것 같습니다.  이와중에 처음엔 단순히 반복문으로만 구현되도록 작성했더니 시간초과가 났습니다. 생각해보니 누적합으로 한다면 반복문을 줄여도 되더라구요. 그냥 딱 그게 핵심이었던 문제였습니다! 
- 처음에는 막연히 DFS로 풀다가 뭔가 이게 아닌 것 같고.. 영 감이 안왔습니다. 그래서 BFS로 풀어보았습니다. 막무가내로 구현하고 알고리즘 분류를 확인해보았는데 플로이드 와샬이 있었습니다. 생각해보니 이 문제는 모든 정점으로부터의 다른 모든 정점으로까지 이어지는지를 판별하는 것이었음을 아차..! 하고 깨닫게 되었습니다. 플로이드 와샬 알고리즘으로도 구현하면 재미있을 문제인 것 같습니다.
- BFS와 DP를 이용해서 풀었습니다. 이 문제는 사이클도 존재하고 가중치도 없다..?고 할수도 있는 그래프 문제이기 때문에 DP를 사용하기 어렵다고 하던데, DP로 푸는 것 이외에는 다른 좋은 방법은 생각이 안나더라구요, priority queue를 이용해서 풀려고도 해봤는데 너무 복잡했습니다. <i>하하... 문제를 풀고 제출하기까지는 얼마 안걸렸으나.. 계속 틀려서 왜 틀렸지하고 1시간을 헤매던 중.. 이 문제는 1번째 자리에서 시작해서 주사위를 던져서 2~7번자리로 나아가는 것인데 저는 0번째 자리부터 시작해서 주사위를 던져 1번에서  6번 자리로 출발하고 시작하는것인 줄 착각했음을 알게되었습니다. 나는 바보.. </i><b>문제를 제대로 읽읍시다..ㅠ.ㅠ</b>
- 하.. 이 문제는 뭐라고 말을 해야할지.. 크게 사용된 알고리즘은 BFS밖에 …

Jaewon / 1월 4주차 / 8문제

---

eodudrepublic/1026_보물.py
eodudrepublic/1157_단어_공부.py
eodudrepublic/1181_단어_정렬.py
eodudrepublic/1427_소트인사이드.py
eodudrepublic/14681_사분면_고르기.py
eodudrepublic/17626_Four_Squares.py
eodudrepublic/2455_지능형_기차.py
eodudrepublic/2711_오타맨_고창영.py
eodudrepublic/2753_윤년.py
eodudrepublic/2884_알람_시계.py

[BOJ] 17626 Four Square 문제는 스터디장님이 푸실때 같이 보기 시작했습니다. 알고리즘 짜고 코드로 구현하는건 40분만에 끝냈는데, break문을 이상한 곳에 넣어서 (어디에 넣었었던건진 기억이 안나네요 ㅠㅠ) 값이 이상하게 나와 1시간 반이나 걸려버린 문제입니다.
알고리즘 분류는 다이나믹 프로그래밍, 브루트포스 알고리즘입니다.
[BOJ] 2711 오타맨 고창영 문제는 여러개의 정수를 입력받을때 map(int, input())을 자주 사용하다보니 여러개의 문자열을 입력받을때도 map()함수를 쓸 뻔 했습니다. 
알고리즘 분류는 구현, 문자열입니다.
[BOJ] 1026 보물 문제는 먼저 문제의 조건(배열 B에 있는 수는 재배열하면 안된다.)을 무시하고 출력만 올바르게 나오도록 먼저 풀고, 문제의 조건에 맞게 또 풀었습니다. 문제를 풀면서 어려웠던 점은 코드에 함께 정리했습니다. 
(근데 조건에 맞게 풀다가 막혀서 QnA 보니까 다들 출력값만 맞게 풀고계셔서 살짝 현타왔던 문제였습니다.)
알고리즘 분류는 수학, 그리디 알고리즘, 정렬입니다.
[BOJ] 1427 소트인사이드는 파이썬 내부 함수를 이용해 입력받은 문자열을 리스트로 만들고, sort() 함수로 리스트를 정렬해 쉽게 해결할 수 있었습니다. 
알고리즘 분류는 정렬입니다.
[BOJ] 1157 단어 공부 문제는 알고리즘 구현 자체는 쉬웠지만 조금 더 짧게 코딩할 수 있지 않을까 하는 아쉬움이 남는 문제였습니다. 그리고 sort() 함수처럼 upper() 함수도 input_str.upper()식으로 사용하면 바로 사용할 수 있을 줄 알았는데, …

eodudrepublic / 1월 4주차 / 10문제

---

llddang/15650_N과M(2).cpp
llddang/17626_FourSquares.cpp
llddang/18870_좌표압축.cpp
llddang/2447_별찍기_10.cpp

17626 Four Squares
시간제한이 0.5초여서 안될것같았는데 다른 방법은 생각나지 않아 일단 해보았는데 됐습니다.
알고리즘 분류
다이나믹, 프로그래밍 브루트포스 알고리즘
2447 별 찍기
처음에 어떻게 해야할수있는지 고민하는것에서 힘들었습니다
알고리즘 분류
분할 정복, 재귀
18870 좌표 압축
처음에
for(auto a:origin){
for(int i=0; i<dd.size(); i++){
if(a <= dd[i]){
cout << i << " ";
break;
}
}
} 으로 했는데 시간 초과가 떠서 찾아보니까 lower_bound라고 stl에서 제공해주는 게 있었다. 설명을 찾아보니까 "범위 [first, last) 안의 원소들 중, value 보다 작지 않은 (크거나 같은) 첫 번째 원소를 리턴한다." 이렇게 되어 있었는데 그럼 내 코드랑 그리 차이가 나는지 모르겠는데 시간 안에 되는 것을 보니 역시 stl 앞으로 좀 더 찾아봐야겠다. 라는 생각을 했다!
알고리즘 분류
정렬, 값 / 좌표 압축
15650 N과 M (2)
재귀를 이용해서 푸는 것에 좀 약한 것 같다!
알고리즘 분류
백트래킹

llddang / 1월 4주차 / 4문제

---

c0np4nn4/2020 카카오 인턴십/[PGS] 키패드 누르기.cpp
c0np4nn4/2021 KAKAO BLIND RECRUITMENT/[PGS] 신규 아이디 추천.cpp
c0np4nn4/2021 카카오 채용연계형 인턴십/[PGS] 숫자 문자열과 영단어.cpp
c0np4nn4/2022 KAKAO BLIND RECRUITMENT/[PGS] 신고 결과 받기.cpp
c0np4nn4/월간 코드 챌린지 시즌1/[PGS] 두 개 뽑아서 더하기

[PGS] 신고 결과 받기
- 프로그래머스의 문제를 Level 1부터 풀어보고자 시작한 문제입니다.
- C++에서 문자열을 다루는 것에 익숙해지기에 좋은 문제인 것 같습니다.
- 다른 언어에서 split() 이나 dictionary 등의 자료구조를 활용한다면 보다 직관적인 코드를 작성할 수 있지 않을까 싶습니다.
* 문제 해결을 위한 사고 과정 자체는 간단했으나 문자열을 다루는 것에 익숙하지 않다면 어려운 문제라고 생각합니다.
* 공부해 볼 만한 점은 16, 17번 줄에서 배열의 크기를 넉넉하게 주어야 문제가 해결된다는 점이었습니다. (문제 조건대로 1,000개의 경우만 고려하면 3, 9, 14, 20, 21 등의 테스트 케이스에서 "실패" 합니다.)
---
[PGS] 신규 아이디 추천
- string 클래스의 erase 메서드를 처음 알게 되었습니다.
- 44번 라인에서 ***id.pop_back()*** 대신에 ***id.erase( id.end() )*** 할 시 segmentation fault가 발생합니다.
- 이는 string::end() 가 past-the-end 반복자기 때문에 발생하는 문제로 보입니다.
- (Ref. https://eehoeskrap.tistory.com/263)
- step 2에서 조건문을 작성할 때 조금 더 신중하게 해야 함을 익혔습니다..
---
[PGS] 숫자 문자열과 영단어
- 어렵지 않은 문제입니다.
- for 문에서 반복자로 사용하는 i 값을 조작할 때는 동작을 잘 생각하여 신중하게 코딩해야 함을 익혔습니다.
---
[PGS] 두 개 뽑아서 더하기
- 일단 브루트 …

c0np4nn4 / 1월 4주차 / 5문제

---

SeongHyun/11286_absoluteheap.py
SeongHyun/1753_shortestpath.py
SeongHyun/234_PalindromeLinkedList.py

**[LTC] Palindrome Linked List / Easy / 50분**
접근 자체는 간단하다고 생각했는데, 코드를 다 짜놓고 보니 포인터가 가리키고 있는 현재 노드를 헷갈려 시간이 조금 소모되었습니다. 전체 연결리스트의 중간을 기준으로 비교해야 겠다고 생각하고 포인터를 두개 사용하여 한번 순회하면서 중간부분을 가리켜놓았습니다. 이후 전체 길이가 홀수일경우 와 짝수일 경우로 나누어 palindrome인지 검사하였습니다.
**[BOJ] 절댓값 힙 / 실버 1 / 20분**
절댓값을 먼저 우선하고 그 다음 원래 숫자를 다음 순위로 하여 (절댓값, 원래값) 으로 힙에 push 하여 풀었습니다.
**[BOJ] 최단경로 / 골드5 / 2시간**
다익스트라 알고리즘 구현할 때, 우선순위 큐를 갖고 구현하면 O(ElogN) 으로 구현이 가능하다하여 관련내용 공부하면서 하다보니,,꽤나 시간이 걸렸습니다. 거기가 시간초과 떠서 어떡하지 하다가 input() 쓴 걸 보고  sys.stdin.readline() 으로 바꿔주었더니 통과 되었습니다.

seonghyun koo / 1월 4주차 / 3문제

---

myeongseo/1009_분산처리.cpp
myeongseo/1011_AlphaCentauri.cpp
myeongseo/1012_유기농배추.cpp

"유기농 배추" 문제는 DFS로 풀었습니다. 풀이 아이디어는 바로 생각났으나 실제로 코드 구현을 어떻게 해야 할지 몰라서 조금 헤맸네요. 
"분산처리" 문제는 간단했으나 나머지가 0인 것을 10으로 바꿔 출력해야 하는 것을 놓쳐서 틀린 부분 찾느라 시간이 좀 걸렸습니다.
"Fly me to the Alpha Centauri"는 이동 거리를 기준으로 1부터 16까지 최소 횟수를 직접 나열해서 규칙 찾았습니다.

myeongseo / 1월 4주차 / 3문제

---

HyeGyoungPark/11399_greedyATM.cpp
HyeGyoungPark/20363_ㅡmathcarrot.cpp
HyeGyoungPark/3135_greedyradio.cpp

[알고리즘 분류]
라디오의 경우 그리디 입니다.
ATM의 경우 그리디, 정렬 입니다.
당근 키우기의 경우 수학 입니다. 알고리즘 분류에는 그리디도 있지만, 수학에 더 가깝게 느껴집니다.
라디오는 실제로 버튼을 누른다고 생각하고 짜니까 금방 생각이 되었습니다. 약간 직관적인(?) 문제라고 생각합니다.
ATM은 왜 코드의 21번 22번 줄을 한 번에 합치고(need += need + line[i] 으로) 그 합친 값(최종 need)을 바로 답으로 출력할 수 없는지 (값이 다르게 나왔습니다.) 잘 모르겠습니다. 연산을 제가 잘못 생각한 것 같은데 왜 안되는지 아직 약간 헷갈립니다.
당근 키우기는 수학적 접근 없이 직괸적으로 조건에 맞을 때 까지 while(1) 과 break로 접근하고 있었다가 규칙을 뒤늦게 발견하였습니다. 규칙만 빨리 발견한다면 매우 빨리 풀 수 있는 문제라고 샐각됩니다.

HyeGyoungPark / 1월 4주차 / 3문제

---

shasuri/4th_week/1288_new_insomnia_treatment.cpp
shasuri/4th_week/linkedlist_training_1.cpp
shasuri/4th_week/linkedlist_training_2.cpp

늦게 풀어서 죄송합니다... 강의 듣는데 급급해서 기초문제만 풀고 있는 저를 용서해주세요...🙏🙏
여유가 되면 4문제 이상으로 풀겠습니다!

shasuri / 1월 4주차 / 3문제

---

seunggil/1759.cpp
seunggil/9663.cpp
seunggil/python/2805.py

[BOJ] 암호 만들기 / 골드5 / 29분 
: 조건에 맞는 경우의 수만 뽑아서 확인하는 단순한 문제.
[BOJ] 나무 자르기 / 실버3 / 1시간 3분 
: 다들 이분탐색으로 풀었는데 나 혼자  DP로 풀었다. 덕분에 난이도가 괴랄해졌다.
나중에 다시 코드 보면 내가 이해 못할꺼 같아서 간단히 적어둠. 
https://shaded-elephant-6e3.notion.site/2805-07d96b48757c41a8a000e4e8fe89b21f
이전부터 느꼈지만 난 자꾸 이분탐색의 존재를 망각하는 문제가 있는거 같다.
[BOJ] N-Queen / 골드5 / 1시간 37분 
: 재귀 +  배열을 쓰면 2초안에 끝나는데,
stack + vector를 쓰면 20분이 지나도 안 끝난다.
코드 안정성 고려하지 말아야겠다.

seunggil / 1월 4주차 / 3문제

---

Ernstjunger-1914/[BOJ]웜홀.cpp
Ernstjunger-1914/[LTC]Add Two Numbers.kt
Ernstjunger-1914/[LTC]Median of Two Sorted Arrays.kt
Ernstjunger-1914/[LTC]Palindrome Number.kt
Ernstjunger-1914/[LTC]Two Sum.kt

이번에는 leetcode 라는 플랫폼에서도 문제를 조금 풀어보았습니다.

Ernstjunger-1914 / 1월 4주차 / 5문제

---

namhee/nh055_boj07568.java

브루트포스 알고리즘 문제입니다!
문제가 긴 거에 비해 구현은 그리 어렵지 않습니다!
Java를 3년 만에 하는 거라 제 코드가 좋은 코드라고 보기는 힘들 겁니다 참고하세요😂
`
(다른 할 게 많아서 이번 주는 한 문제만 냅니다... 죄송해요ㅠㅠ)

namhee / 1월 4주차 / 1문제

---

thkang727/10826_피보나치수열4.py
thkang727/11053_가장긴증가하는부분수열.py
thkang727/2579_계단오르기.py

이번주는 저번주에 이어 DP 문제들을 3문제를 이어서 풀었습니다.
지난번에 풀면서 느꼈는데, 전공수업을 어떻게 들었는지 신기할 정도로 DP 개념이 없더라구요. 그래서 관련 유튜브 강의도 보면서 첨부터 다시 풀어보았습니다!
우선 피보나치 수열4(10826) 문제는 DP하면 나오는 기본 개념 문제기도 하고, 파이썬으로 알고리즘 문제를 푸는 첫 문제라 가볍게하려고 골랐습니다. DP 개념을 따라 앞에 나온(풀어놓은)값을 이용하여 다음 피보나치수를 구하는 문제여서 쉽게 풀이했습니다.
2579 문제도 DP의 기본 문제라고 하여 선택하였습니다.  그러나 풀이가 지연되었는데, 그 이유인 즉슨, 개념에서 2칸 아래 dp값 과 3칸 아래 dp값+1칸 아래 계단 값 을 비교하는 것이 아닌 계단 값을 비교하기도 했고, 비교는 제대로 해놓고 이전 dp값이 아닌 계단 값을 넣는 등의 잘못된 판단이 있었습니다. 그리고 원인 모를 index error가 계속 떠서,,, 그냥 다 지우고 다시 풀었어요.
가장 긴 증가하는 수열은 어떤 조건에서 길이를 +1해주는지 찾는 규칙이 찾기 힘들었습니다. 단순히 앞의 값보다 큰 값을 넣으면 안돼었기에, dp값 까지 비교하여 넣어주었습니다. 은근히 문제 규칙찾기에서 헤매었습니다.
다음주까지도 dp 관련 문제풀이를 할 것이고, 이번에는 골드 문제도 1문제 도전해보려합니다!

thkang727 / 1월 4주차 / 3문제

---

Jeonghak/2309_일곱난쟁이.cpp
Jeonghak/6064_카잉달력.cpp
Jeonghak/6588_골드바흐의추측.cpp

카잉달력은 완전 탐색 문제이고 M, N 중 하나를 기준으로 잡아서 불필요한 반복을 줄일 수 있는 규칙을 찾는 것이 중요했습니다. 
일곱 난쟁이 문제도 완전 탐색 문제이고 시간이 없어서 쉬운 문제를 빠르게 풀었습니다.. 
골드바흐의 추측 문제는 에라토스테네스의 체를 모르고 있었어서 푸는 데 많은 시간이 걸렸습니다.

Jeonghak / 1월 4주차 / 3문제

---

namhee/nh056_sea01204.java
namhee/nh057_sea01206.java
namhee/nh058_sea01208.java
namhee/nh059_sea01220.java
namhee/nh060_boj02628.java

이번 주에 푼 문제는 "적절한 자료구조 선택과 반복/제어문"으로 문제 해결이 주가 되는 문제들입니다!
난이도는 모두 쉽지만, 문제를 잘 읽는 습관을 들이지 못했다면 돌아가기 쉬운 문제들이었어요.
이제까지는 문제 풀면서 풀었던 메모들을 지우고 올렸는데 앞으로는 지우지 않고 올리기로 했습니다😃 (맨 아래쪽에 있어요.)
SEA를 처음 써봐서 실수 한 부분이 기억에 남습니다.
Runtime error가 발생한다면, 아래를 먼저 체크하기로 했습니다.
1. 입력한 형태가 입력 예제 텍스트와 일치하는지 확인
2. class명이 Solution인지 확인
특히, 컴파일할 때는 런타임 에러가 발생하지 않는데 제출할 때만 런타임 에러가 발생한다면 1번 원인일 가능성이 늪았어요.
(물론 예제에서 주어진 테스트케이스 외의 경우에서 runtime error를 발생시킬 원인이 생겼을 수도 있겠지만요.)
앞으로 코드 옮길 때 꼼꼼히 보기로 했습니다!

namhee / 1월 5주차 / 5문제

---

GomGom9/[LTC][0217][easy] Contains Duplicate.py
GomGom9/[LTC][0387][easy] First Unique Character in a String.py
GomGom9/[LTC][1608][easy] Special Array With X Elements Greater Than or Equal X.py

GomGom9 / 1월 5주차 / 3문제

---

lysuk96/Week5/05_PGS_더맵게.py
lysuk96/Week5/05_PGS_디스크컨트롤러.py
lysuk96/Week5/05_PGS_베스트앨범.py
lysuk96/Week5/05_PGS_위장.py
lysuk96/Week5/05_PGS_이중우선순위큐.py
lysuk96/Week6/06_PGS_모의고사.py
lysuk96/Week6/06_PGS_방의개수.py
lysuk96/Week6/06_PGS_소수찾기.py
lysuk96/Week6/06_PGS_주식가격.py
lysuk96/Week6/06_PGS_체육복.py
lysuk96/Week6/06_PGS_카펫.py
lysuk96/Week6/06_PGS_타겟넘버.py

저번주에 pr을 안올려서 이번에 한번에 올립니다! ㅎㅎ

lysuk96 / 1월 5주차 / 12문제

---

llddang/1149_RGB거리.cpp
llddang/9184_신나는함수실행.cpp
llddang/9461_파도반수열.cpp

9184_신나는 함수 실행
저장해서 가져오는 문제를 풀어본적이 있어서 어렵지 않았다
알고리즘 분류
다이나믹 프로그래밍, 재귀
9461_파도반 수열
어렵지는 않았는데
dp[1] = 1;
dp[2] = 1;
dp[3] = 1;
dp[4] = 2;
dp[5] = 2;
dp[6] = 3;
dp[7] = 4;
dp[8] = 5; 이 부분을 깔끔하게 어떻게 적을 수 있는지 모르겠다..
알고리즘 분류
수학, 다이나믹 프로그래밍
1149_RGB거리
제가 쓰는 코드는 한 눈에 바로 들어오지 않는 것 같습니다.. 
혹시 이 부분 어떻게 고칠 수 있는지 조언가능한가요?
알고리즘 분류
다이나믹 프로그래밍

llddang / 1월 5주차 / 3문제

---

myeongseo/1013_contact.cpp
myeongseo/1015_수열정렬.cpp
myeongseo/1016_제곱ㄴㄴ수.cpp

[1013_Contact] 
중간에 오답 처리가 되어서 뭐가 문제인지 한참 들여다봤네요...
알고보니 first함수에서 마지막에 1을 반복하여 계산하다 보니 10011001에서 1001을 하나의 신호로 계산하지 않고 10011을 하나의 신호로 계산하는 오류가 있었습니다. 
그래서 second 함수에서 이를 고려하도록 수정했습니다.
[1015_수열정렬]
문제 자체가 이해 안되어서 고민하다가 결국 다른 사람이 예제로 해석해 놓은 거 보고 이해했습니다.
문제 이해와 달리 코드는 priority queue의 정렬 기능을 이용해서 쉽게 짤 수 있었습니다.
[1016_제곱ㄴㄴ수]
처음에는 set의 중복 방지 기능을 사용해서 제곱으로 나눠떨어지는 수의 갯수를 구하는 방식으로 코드를 작성했습니다.
하지만 시간초과가 떠서 cin과 cout, endl을 scanf, printf, \n로 바꾸는 등 여러 시도했지만 계속 시간초과가 났습니다...
결국 set을 포기하고 배열로 중복을 체크하는 방식으로 바꿔서 재작성해서 통과했습니다...

myeongseo / 1월 5주차 / 3문제

---

c0np4nn4/[BOJ] 17413_단어 뒤집기 2.cpp
c0np4nn4/[BOJ] 2579_계단 오르기.cpp
c0np4nn4/[BOJ] 9655_돌 게임

이번 주.. 도저히 3문제 이상 풀 짬이 나지 않았습니다...ㅜㅜ
"문자열" : 단어 뒤집기 2
"DP" : 돌 게임, 계단 오르기

c0np4nn4 / 1월 5주차 / 3문제

---

jaewon/17404_RGBRoad2.cpp
jaewon/20040_cycleGame.cpp
jaewon/4386_makeConstellation.cpp

- MST문제. 크루스칼 알고리즘을 사용하는 것은 알았으나 사이클 검사를 어떻게 해야하는지 몰라서 많이 틀렸다.
- 사이클 검사는 union_find를 이용하는 건데 union_find의 과정에서 find를 사용하지 않으면 parent 저장소가 업데이트가 안된다는 것을 간과했다.
- 소수점 자리수 제한하는 법으로 precision을 사용하는 것보다 그냥 printf("%.2f",~~)를 사용하는 것이 맞는 것 같다.
- 흔한 DP문제
- 처음 집과 마지막 집의 조건 때문에 DP를 3개로 나누어서 풀었다.
- union_find만 알면 풀 수 있는 문제.

Jaewon / 1월 5주차 / 3문제 

---

dmstj920/10825_국영수.cpp
dmstj920/12865_평범한배낭.cpp
dmstj920/1475_방번호.cpp

알고리즘 분류 : [1475] 구현 / [10825] 정렬 / [12865] DP
[1475] 방 번호
- 6과 9가 포함되는 경우만 잘 생각한다면 쉽게 풀 수 있었던 문제였습니다. 처음에 방번호에서 중복되는 숫자가 하나인 경우만 생각하여 틀렸는데 생각하다보니 최댓값을 더하면 된다는 것을 알 수 있었습니다. 
[10825] 정렬
- 저번 주에 풀었던 [10814] 나이순 정렬 문제에서 정렬 조건이 더 많아진 문제입니다. 구조체 정렬 문제를 한번 더 복습하고 싶어서 풀게 되었습니다.
[12865] 평범한 배낭
- 처음 접근을 가치 순으로 정렬하고 for문을 이용하여 더해가면서 최댓값을 찾으려고 했는데 어떻게 해도 반례가 생겨서 결국 구글링을 하여 참고하게 되었습니다. (https://yabmoons.tistory.com/571 , https://cocoon1787.tistory.com/206) 
- DP를 이용해서 문제를 풀어본 적이 없어서 이런 접근법은 생각조차 못했었는데 이 문제를 계기로 여러 DP문제를 풀어봐야겠다는 생각을 했습니다.

dmstj920 / 1월 5주차 / 3문제

---

shasuri/5th_week/10726_binary_expression.cpp
shasuri/5th_week/bfs_training.cpp
shasuri/5th_week/dfs_training.cpp

이번주에 알고리즘에 너무 소홀했던 것 같습니다... 죄송합니다...

shasuri / 1월 5주차 / 3문제

---

thkang727/10815_숫자카드.py
thkang727/11722_가장 긴 감소하는 부분 수열.py
thkang727/11726_2×n 타일링.py

이번주 3문제는 DP 2문제와 문제은행에서 소개받은 이중탐색 문제 1문제를 풀이했습니다. 실버4,실버3,실버2의 난이도를 가졌습니다.
이중탐색 문제는 처음에는 단순구현/브루투 포스 방식으로 생각을 하여 풀이를 했으나, 그러면 시간초과가 된다는 것을 알고, 이중탐색 방법을 사용하였습니다. 기본적인 이중탐색 방법(낮은값, 높은값, 중앙값) 비교를 하는 방법으로 어렵지는 않았으나 이중탐색의 while문 탈출 조건을 같을때만 표기해주고, 배열 전체에서 다를때인 경우는 표기를 하지 않아, 런타임 에러가 떳었습니다.
DP 두 문제는 지난주처럼 문제은행에서 소개받은 문제들을 풀었습니다. 2문제 모두 큰 문제 없이 풀었고, '가장 긴 감소하는 부분 수열' 문제는 지난번에 풀이한 '가장 긴 증가하는 부분 수열'문제와 풀이법이 거의 같아 쉽게 풀이했습니다.
이번주는 시간 부족으로 계획했던 골드문제 풀이를 시도하지 못했으나, 다음주는 꼭 하려합니다!

thkang727 / 1월 5주차 / 3문제

---

seunggil/15686.cpp
seunggil/17070.cpp
seunggil/17144.cpp
seunggil/python/1991.py
seunggil/python/test.py

자바, 파이썬, c++ 번갈아가면서 사용하니 머리가 너무 복잡하다..
[BOJ] 트리 순회 / 실버1 / 41분
:C++로 하면 20분도 안걸리는 문제인데..
파이썬으로 하니까 족쇄가 있는 기분.
[BOJ] 파이프 옮기기 1 / 골드5 / 1시간 20분
: 무난히 dfs로 풀었는데, 이걸 dp로 풀 수도 있다고 한다.. 다음에 재도전
[BOJ] 치킨 배달 / 골드5 / 1시간 9분
:브루트포스로도 시간이 충분하다는 걸 확신하지 못하여 여러 시도를 했으나,
빠르지도 않은 이상한 코드가 나왔다.
[BOJ] 미세먼지 안녕! / 골드4 / 2시간
:어렵지는 않은데 구현할게 더럽게 많다.

seunggil / 1월 5주차 / 4문제

---

eodudrepublic/12871_무한_문자열.py

[BOJ] 12871 무한 문자열 문제는 1월 5주차 때 '파이썬은 속도가 느리니까 먼저 확인할 수 있는 조건을 먼저 확인하는 방법으로 알고리즘을 짜면 되지 않을까?'란 생각으로 밑의 주석처리된 코드를 작성했으나, 2월 1일 추석 당일까지 2시간 동안 못 풀고(...) 결국 제일 단순한 방법을 이용해 풀게 되었습니다, 5분만에. ...진작 이렇게 풀걸 그랬네요.
알고리즘 분류는 수학, 구현, 문자열입니다.

eodudrepublic / 2월 1주차 / 1문제

---

dmstj920/1463_1로만들기.cpp

알고리즘 분류 : [1463] DP
**[1463] 1로 만들기**
- DP 관련 문제를 더 연습하고 싶어서 풀어보았습니다. 아무리 생각해도 접근법이 잘못된 것 같아 다른 분의 코드를 참고하게 되었습니다. 너무 간단해서 좀 충격받았...ㅎㅠ
- 알게된 점: 점화식을 생각하자!!

dmstj920 / 2월 1주차 / 1문제

---

HyeGyoungPark/9655_mathstonegame.cpp
HyeGyoungPark/9656_mathstonegame2.cpp

[알고리즘 분류]
돌 게임_9655 : 수학, DP
돌 게임2_9656 : 수학, DP
[돌 게임_9655]은 DP 문제를 풀어보자! 하고 쉬운 것 부터 차근차근 해보려 했는데 수학적으로 생각하니 금방 끝나서 결과적으로 DP를 풀려고 했으나 DP로 풀지 않은 문제가 되었습니다. 조금 아쉬우니 다음번에 DP로도 접근을 해 보려구요! 근데 그러면 시간이 수학적인 접근보다 더 늦어지지 않을까? 하는 궁금증은 조금 있습니다. 수학적 접근이 이 문제는 조금 더 빠르지 않을까요?!
[돌 게임2_9656] 는 2가 있길래 조금 더 어려울까 싶어 DP로 풀어보자 하고 봤는데 1과 이기고 지는 사람만 반대인 경우였습니다. 아마 돌을 가져가는 개수가 좀 달라지면 DP로 접근하는 방식이 더 빠르게 될 것 같은데 이 문제는 수학적 접근이 빠르지 않을까 싶습니다..

HyeGyoungPark / 2월 1주차 / 2문제

---

lysuk96/Week7/07_뉴스클러스터링.py
lysuk96/Week7/07_다트게임.py
lysuk96/Week7/07_방금그곡.py
lysuk96/Week7/07_비밀지도.py
lysuk96/Week7/07_셔틀버스.py
lysuk96/Week7/07_압축.py
lysuk96/Week7/07_캐시.py
lysuk96/Week7/07_프렌즈4블록.py

카카오 2018 1차 기출을 풀어보았읍니다
난독증이 와서 어려웠읍니다!

lysuk96 / 2월1주차 / 8문제

---

llddang/1037_약수.cpp

llddang / 2월 1주차 / 1문제

---

myeongseo/1018_체스판다시칠하기.cpp

[체스판 다시 칠하기]
모든 8*8 크기의 경우에 대해 1.흰색으로 시작하는 경우  2.검은색으로 시작하는 경우 둘 다 직접 세는 방식으로 문제를 풀었습니다.

 myeongseo / 2월 1주차 / 1문제

---

SeongHyun/20_validParentheses.py
SeongHyun/21_mergeTwoList.py
SeongHyun/23_mergeKList.py
SeongHyun/24_swapPairs.py

[LTC] Merge k Sorted Lists / Hard / 1시간]
[LTC] Merge Two Sorted Lists / Easy / 10분]
-->연결리스트를 힙에 push하고 pop하면서 정렬순서대로 다시 연결리스트 생성하였습니다.
[LTC] Swap Nodes in Pairs / Medium / 20분]
-->deepcopy하지않고 단순히 리스트를 할당(shallowcopy)하면 주소값이 할당된다는 걸 이용하여 result에 연결리스트 맨앞을 저장해두고 두개씩 swap 한후에 result를 반환하였습니다.
[LTC] Valid Parentheses / Easy / 30분]
-->스택을 이용하여 '괄호문자'의 대응을 체크하였습니다.

seonghyun koo / 2월 1주차 / 4문제

---

GomGom9/[LTC][0125][easy] Valid Palindrome.py
GomGom9/[LTC][0155][easy] Min Stack.py
GomGom9/[LTC][0412][easy] Fizz Buzz.py
GomGom9/[LTC][206][easy] Reverse Linked List.py

GomGom9 / 2월 1주차 / 4문제

---

thkang727/2225_합분해.py
thkang727/2631_줄세우기.py

이번주도 역시 DP 관련 문제 풀이를 해보았습니다. 이번에는 DP 관련 풀이 실버 수준 문제를 어느정도 풀어봐서 골드를 도전해봤습니다.  전체적으로 느낀 것은 골드5 수준을 해보았는데, 대놓고 DP 느낌이 아닌걸 주는 것 뺴고는 크게 실버 수준 문제랑 다르지 않았던 것 같습니다. 살짝 실버 문제에서 살짝 꼬은 느낌이 있었던 것 같습니다.
'합분해' 문제의 경우, 처음 볼 때 합의 수 와 나누는 수 2가지만을 가지고 나오는 경우의 수를 어떻게 구해야 하는지 생각했습니다. 처음에 이를 DP로 구하는 것은 어렵다고 생각했습니다.  그래서 일일이 케이스를 메모장에 끄적여 보던중 합의 수를 하나의 수로만 나타낼때와 1을 여러 수로 나타낼때의 경우의 수가 어느 경우에서든 같은 공식임을 확인했습니다.
(합의수 : 1 일때, 나누는 수 :n 이면 경우의 수 n.  합의수 : k 일때, 나누는 수 : 1이면 경우의 수 1.)
그래서 점화식을 구해서 다음항을 구하여 나타낼 수 있었습니다.
'줄세우기' 문제의 경우에는 이전에 풀었던 증가하는 수열 문제와 거의 같았습니다.
가장 긴 증가 수열의 수를 구하여, 전체항에서 빼주면 됩니다.
다음 주차에도 DP 관련 골드문제를 풀이해보겠습니다

thkang727/ 2월 1주차 / 2문제

---

shasuri/4th_week/1288_new_insomnia_treatment.cpp
shasuri/6th_week/3316_manage_club_room.cpp

벼락으로 푼것도 있고... 많이 당황스러운 문제였습니다...

shasuri / 2월 1주차 / 1문제

---

SeongHyun/13414_sugang.py
SeongHyun/148_sortList.py
SeongHyun/347_topKfrequent.py

**[LTC] Sort List / medium / 20분]**
연결리스트를 O(nlogn) 로 정렬하는 문제여서, 리스트에 담은후 내장함수인 sort()를 사용하여 정렬했습니다. 나중에 여유로울때 병합/퀵/힙 정렬로도 직접 짜보면 좋을것 같습니다만 퀵은 운이나쁘면 time-out 일수도
**[BOJ] 수강신청 / 실버3 / 40분]**
처음에 중복제거를 위해 set을 이용했지만 집합에 순서가 없다는걸 뒤늦게 알고, 새로 딕셔너리를 이용해 순서를 입력하여 풀었습니다! 없을땐 새로 삽입, 있으면 덮어쓰기. 그랬는데도 틀려서 왜그런가 했더니 sys입력이 개행도 문자열로 받고있어서 strip()으로 제거해주고 통과했습니다
**[LTC] Top K Frequent Elements / medium / 20분]**
collection모듈에 counter를 이용하여 빈도를 구하고 힙에 push&pop 하여 상위 k개만 구했습니다.

seonghyun koo / 2월2주차 / 3문제

---

HyeGyoungPark/15736_mathbluewhiteflag.cpp
HyeGyoungPark/1946_greedynewcrew.cpp
HyeGyoungPark/6588_mathGoldbach.cpp

[알고리즘 분류]
6588_골드바흐의 추측 : 수학, 소수판별
15736_청기 백기 : 수학
1946_신입 사원 : 그리디, 정렬
[6588] 의 경우 소수 판별만 빠르게 해결하면 풀 수 있었습니다! 다만 처음 제출했을 때 100%에서 시간초과가 나서 뭐지? 했는데 std::cin.tie(NULL); std::ios::sync_with_stdio(0); 이 부분을 추가해주니까 통과 되었습니다. 시간초과는 저 부분을 늘 고려해보아야 하는 것 같아요. 그런데 저 부분은 혹시 백준 한정인가요? 아니면 다른 코테 시험이나 그럴 때도 추가를 해 주는 것이 안전할까요? 조금 궁금합니다! 
[15736] 청기 백기의 경우 처음에는 리스트에 하나하나 바꿔주는걸 반영해야 하는가? 고민을 하는 데에 시간이 조금 걸렸습니다. 바로바로 계산을 할 방법을 생각해보니 의외로 간단하게 규칙이 나와서 역시 규칙성을 찾는 것이 중요하다는 걸 다시 생각했습니다!
[1946] 신입 사원은 뭔가 알 것 같은데 정렬 후 사원을 뽑는 기준을 생각하는 데에서 조금 시간이 오래 걸렸습니다. 계속 아 이거 뭔가 보이는데 알 거 같은데 에서 생각보다 쉽게 바로 안나오더라구요. 약간 말 하다가 까먹어서 뭐더라 뭐더라 뭐더라? 하는 기분으로 계속 문제를 풀었습니다! 그리고 맨 처음 제출했을 때 통과해서 오! 했는데 같은 코드로 또 제출하니 시간 초과가 나오더라구요! 그래서 또 [6588] 에 추가했던 걸 추가해서 다시 제출했었습니다. 시간초과! 참 오묘합니다.

HyeGyoungPark / 2월 2주차 / 3문제

---

myeongseo/1021_회전하는큐.cpp
myeongseo/1024_수열의합.cpp
myeongseo/1026_보물.cpp

[회전하는 큐]
왼쪽으로 이동시키는 경우와 오른쪽으로 이동시키는 경우 모두를 구해 더 작은 이동을 한 방향으로 더해주는 방식으로 문제를 풀었습니다.
저번에 queue나 vector등에 넣었다가 빼는데 생각보다 시간이 오래 걸린다는 사실을 알게 되어 최대한 안 쓰는 방법으로 풀려고 하다보니 오히려 더 복잡하게 문제를 푼 것 같습니다.
수학적으로 접근했더니 답이 틀렸을 때 문제점을 알기 더 어렵고 머리 아프네요...
[수열의 합]
옛날에 풀었던 수학 문제와 비슷해 쉽게 풀이법을 떠올릴 수 있었습니다.
[보물]
원래 B는 재배열하면 안되지만 합 결과만 출력하기 때문에 B도 그냥 크기 순으로 재배열해서 풀었습니다.
정렬만 하면 쉽게 풀 수 있는 문제였습니다.

myeongseo / 2월 2주차 / 3문제

---

shasuri/7th_week/1230_cipher3.cpp
shasuri/7th_week/13469_notepad.cpp
shasuri/7th_week/13501_editing_num_array.cpp

메모장 프로그램은 덜 푼건데;; 6시까지 최대한 노력해보겠습니다...

shasuri / 2월 2주차 / 3문제

---

llddang/11726_2xn타일링.cpp
llddang/1932_정수삼각형.cpp
llddang/9095_123더하기

1932 정수 삼각형
dp문제 처음으로 dp답게 푼 것 같습니다!! 뿌듯합니당!
알고리즘 분류
다이나믹 프로그래밍
9095 1, 2, 3 더하기
점화식 세우는게 힘듭니다 7까지 손수적어보고 무슨 연관이 있는지 찾았습니다!
알고리즘 분류
다이나믹 프로그래밍
11726 2xn 타일링
이번에도 5까지 적어보고 찾았습니다! 보고 논리로 바로 떠오르면 좋겠지만 아직은 그렇게 안될것같습니다ㅜㅜ
알고리즘 분류
다이나믹 프로그래밍

llddang / 2월 2주차 / 3문제

---

thkang727/1149_RGB거리.py
thkang727/11660_구간 합 구하기 5.py
thkang727/1476_

이번주는 DP 2문제와 문자열 1문제를 풀었습니다.
구간 합 구하기 5 문제의 경우 시간초과를 안하기 위해 코드 수정을 여러 번 했습니다. 코드구성 자체는 DP 문제의 2차원 배열을 이용한 빠른길찾기 문제와 비슷하였으나, 시간초과로 인해 시간이 좀 더 걸렸습니다.

thkang727 / 2월 2주차 / 3문제

---

myeongseo/1027_고층건물.cpp
myeongseo/1037_약수.cpp
myeongseo/1049_기타줄.cpp

[고층 건물]
처음에는 앞에 높은 건물이 있으면 뒤의 건물은 보이지 않을 거라는 생각으로 접근을 시도했으나 예제에 적용해보다가 잘못 이해했음을 깨달았습니다. 각 건물을 그래프로 배치해보고 건물이 보이는 것의 여부는 두 건물 사이의 각도임을 알게되었습니다.
그리고 double = int/int는 int로 계산 후 double로 바뀌는 것을 항상 주의하자!! 또한 소수점 오차가 중요할 때는 float보다는 double을 사용합시다ㅏ!!
[약수]
약수를 나열할 때 보통 앞/뒤로 짝 지어 적었던 걸 생각해서 쉽게 풀 수 있었습니다.

myeongseo / 2월 3주차 / 3문제

---

HyeGyoungPark/1037_mathdivisor.cpp
HyeGyoungPark/17103_mathGoldbachEratosChe.cpp
HyeGyoungPark/4796_mathCamping.cpp

[알고리즘 분류]
1037_약수 : 수학, 정수론
17103_골드바흐 파티션 : 수학, 정수론, 소수 판별, 에라토스테네스의 체
4796_캠핑 : 수학, 그리디
1037 약수는 카테고리에 정렬도 있으면 좋지 않았을까 싶습니다~!
17103 골드바흐 파티션은 이전에 골드바흐의 추측을 풀었었으니 이걸 활용하면 되지 않을까? 해서 풀었습니다. 그런데 이전에 했던 풀이로 풀면 시간초과가 나서 해당 문제 질문글에 들어가보니 에라토스테네스의 체를 이용해야 하는 것 같더라구요! 그래서 에라토스테네스의 체를 이용하고 이를 계속 누적해서 소수 판별을 하여 시간 초과를 해결했습니다. 에라토스테네스의 체가 확실히 되게 빨라서 알면 좋겠다! 싶습니다~!
4796 캠핑은 수학으로 풀었습니다! 사실 맨 처음에 문제 이해도 조금,, 헷갈렸는데 좀 더 간단하게 생각하면 이해가 되더라구요! 근데 실제 캠핑이라고 생각하고 더 알차게(?) 쓰려면 좀 더 즐길 수도 있을 것 같은데 아무튼 그랬습니다! 나누고 남은 일자 세는 거에서 처음 코드는 틀렸다고 떠서 왜지? 왜지? 하다 보니 남은 수가 가능한 수 보다 클 수도 있겠더라구요. 그걸 찾는 데에서 좀 헤맸습니다.

HyeGyoungPark / 2월 3주차 / 3문제

---

dmstj920/1037_약수.cpp
dmstj920/1735_분수합.cpp
dmstj920/2822_점수계산.cpp

알고리즘 분류 : [1037] 수학, 정수론 / [2822] 정렬 / [1735] 수학, 정수론, 유클리드 호제법
**[2822] 점수 계산**
- 정렬만 잘 하면 쉽게 풀 수 있는 문제 였는데 조금 더 간단히 푸는 방법이 있을 것 같아서 더 고민해보려고 합니다.

dmstj920 / 2월 3주차 / 3문제

---

shasuri/8th_week/1012.py
shasuri/8th_week/1786.cpp
shasuri/8th_week/1970_easy_change.cpp

아이고... 한번에 푸쉬한점 양해부탁드립니당... 방학이 끝나가는데 점점 바빠지네요... 미리미리 해둘걸

shasuri / 2월 3주차 / 3문제

---

SeongHyun/17_letterCombinations.py
SeongHyun/46_permutation.py
SeongHyun/77_combinations.py

**[[LTC] Letter Combinations of a Phone Number / medium / 50분]**
3중 for문 상당히 치명적이어 보이지만... 최대숫자길이가 4밖에 되지않고 모든 조합을 탐색해야하기 때문에 어떻게 짜도 비슷할거라 보고 과감히 반복문 세개를 겹쳐보았습니다.
**[LTC] Permutations / medium / 2시간]**
재귀함수로 짜다가 머리가 너무 복잡해져서 그림그려보고 쓱싹쓱싹 하다보니 시간이 조금 오래걸렸습니다. 수학시간에 순열 배울때 하나씩 뽑아서 배치하는 컨셉 처럼 리스트에서 뽑은건 없애는 방식으로 구현하였습니다.
**[LTC] Combinations / medium / 5분]**
위 문제를 다풀고 다른사람은 어떻게 풀었나 보다가 itertools라는 모듈이 있는 것을 보고 이문제에 적용하여 보았습니다.
단한줄에 풀리는 마법.

seonghyun koo / 2월 3주차 / 3문제

---

lysuk96/Week9/09_BOJ_NQueen.py
lysuk96/Week9/09_BOJ_로또.py
lysuk96/Week9/09_BOJ_별찍기10.py
lysuk96/Week9/09_BOJ_암호만들기.py
lysuk96/Week9/09_BOJ_연구소.py
lysuk96/Week9/09_BOJ_하노이탑이동순서.py

lysuk96 / 2월3주차 / 6문제

---

dmstj920/1026_보물.cpp
dmstj920/16435_스네이크버드.cpp
dmstj920/2609_최대공약수와최소공배수.cpp

알고리즘 분류 : [1026] 수학, 그리디, 정렬 / [16435] 그리디, 정렬 / [2609] 수학, 정수론, 유클리드 호제법
**[1026] 보물 / [16435] 스네이크버드** 
- 정렬만 잘하면 쉽게 풀 수 있었던 문제입니다.
**[2609] 최대공약수와 최소공배수**
- 항상 유클리드 호제법을 이용하여 최대공약수 구하는 알고리즘이 헷갈렸었는데 이 문제를 통해 확실히 알게 되었습니다.

dmstj920 / 2월 4주차 / 3문제

---

HyeGyoungPark/11650_sortXYsort.cpp
HyeGyoungPark/14469_sortCowacross.cpp
HyeGyoungPark/16435_sortSnakebird.cpp

[알고리즘 분류]
스네이크 버드, 소가 길을 건너간 이유3 : 정렬, 그리디
좌표 정렬하기 : 정렬
스네이크 버드는 맨 처음에 순서대로 입력된 걸로 해야하는 줄 알고 풀었는데 값이 너무 달라서 문제 이해를 다시 하는 데에 시간이 좀 더 걸렸습니다. 스네이크 게임이 생각나서 재밌었어요~!
좌표 정렬하기는 예전에 벡터의 인자로 pair를 쓴 적이 있는데 Pair 사용 연습을 더 해보고 싶어서 풀었습니다! 구조체로 만들어서 푸는 방법도 있을 것 같습니다~!
소가 길을 건너간 이유3은 예전에 약간 비슷한 문제로 무슨 면접관이 서류 통과하는 문제(?)가 생각 났습니다. 그 때 처럼 이 문제도 약간 기준점을 잡는 것에 있어서 아리까리한 상태로 좀 지연돼서 머리가 좀 아팠습니다. 아무래도 이런 느낌의 문제 조건을 저는 조금 바로바로 생각하지 못하는 듯 싶어요. 좀 더 연습해야겠습니다~!

HyeGyoungPark / 2월 4주차 / 3문제

---

Ernstjunger-1914/[BOJ]미로 탐색.cpp
Ernstjunger-1914/[BOJ]요세푸스 문제 3.cpp
Ernstjunger-1914/[BOJ]통계학.cpp

통계학 같은 경우, 예전에 풀었는데 재채점되어 틀려서 다시 풀었습니다.

Ernstjunger-1914 / 2월 4주차 / 3문제

---

eodudrepublic/14654_스테판_쿼리.py
eodudrepublic/7567_그릇.py
eodudrepublic/8958_OX퀴즈.py

[BOJ] 스테판 쿼리 문제는 아래에 주석 처리된 방법으로 약 1시간 반 가량 풀었으나, 계속 오답이 떠 보기 쉽게 함수식으로 정리해보고 틀린 부분을 찾으려 해보니 풀린 (...) 상당히 어이없었던 문제입니다. 혹시 제가 주석처리한 코드가 왜 틀렸는지 알려주실 분 계신가요 ㅠㅠ
알고리즘 분류는 구현과 시뮬레이션입니다.
[BOJ] OX퀴즈는 단순 구현, 문자열 문제로 간단하게 풀었습니다.
[BOJ] 그릇 문제는 OX퀴즈와 동일한 구현, 문자열 문제로 동일한 방식으로 풀었습니다.

eodudrepublic / 2월 4주차 / 3문제

---

myeongseo/1032_명령프롬프트.cpp
myeongseo/1260_DFS와BFS.cpp
myeongseo/2178_미로탐색.cpp

[DFS와 BFS]
처음에는 간선이 연결된 관계를 map으로 풀다가 너무 복잡하게 푸는 거 같아서 다른 사람의 코드를 좀 참고 했습니다. 배열로 관계를 나타내면 훨씬 간단하게 표현할 수 있고 함수를 짤 때에도 접근이 편해서 좋았습니다.
[미로 탐색]
앞의 문제를 풀고 dfs, bfs를 활용한 다른 문제를 풀어보고자 해서  시도해 본 문제입니다. 이전 문제를 응용해 혼자 풀 수는 있었지만 아직 실력이 미흡해서 중간 중간 실수가 많았던 거 같습니다. 해당 문제는 bfs로 접근했습니다.
[명령 프롬프트]
각 문자열의 차이점만 판단하면 되어서 쉽게 풀 수 있었습니다.

myeongseo / 2월 4주차 / 3문제

---

shasuri/10th_week/2930_heap.cpp
shasuri/10th_week/4408_return_to_room.cpp

shasuri / 2월 4주차 / 2문제

---

9237_sortinviteEJang.cpp
HyeGyoungPark/1010_mathDPbridge.cpp
HyeGyoungPark/11651_sortXYsort2.cpp

[알고리즘 분류]
다리 놓기(1010) : 수학, DP
좌표 정렬하기2(11651) : 정렬
이장님 초대(9237) : 정렬
다리 놓기는 조합을 생각하니 코드 방식은 금방 짰는데 시간 초과를 해결하는 곳에서 좀 시간이 걸렸습니다. DP로 접근을 하려는데 하나씩 저장을 어떻게 해야하지 그런 생각이 들더라구요! 그러다가 해결되었습니다. DP는 참 멋진 것 같아요.. 
좌표 정렬하기2는 전에 1을 풀었었어서 뭐가 다른지 궁금해서 풀었습니다! sort 함수를 새로 짜는데 bool로 짜야하는가에서 약간 고민을 했습니다. pair로 인자를 넣으면 sort를 편하게 할 수 있어서 좋은 것 같아요!
이장님 초대는 쉬운 문제였는데 약간 생각을 거꾸로 해서 시간이 오래 걸렸습니다. 정렬 너무 좋아요. algorithm 라이브러리 짱.. 그거랑 별개로 vector에 scanf로 입력을 받아서 한 번에 넣고 싶었는데 그거는 이상하게 잘 안되는 것 같더라구요. 그래서 그냥 배열을 썼는데 혹시 메모리 초과가 나지는 않을까 조금 조마조마했습니다ㅎ.ㅎ.. 
for(int i=0; i<n; i++){
scanf("%d",&tree[i]);
}
이 부분을 최종 코드는 int *tree = new int[n] 으로 해서 배열로 했지만 저 tree를 vector <int> tree 로 할 수는 없는지..! 제가 뭔가 코드를 잘못 짠 거였겠지만 아무튼 왜 안되었을까! 궁금하네요..

HyeGyoungPark / 3월 1주차 / 3문제

---

dmstj920/1292_쉽게푸는문제.cpp
dmstj920/14729_칠무해.cpp
dmstj920/3036_링.cpp

알고리즘 분류 : [3036] 수학, 정수론, 유클리드호제법 /  [14729] 정렬 / [1292] 수학, 구현
**[14729] 칠무해**
- c++에서 소수점 이하 몇 자리가 나오게 하는 방법을 몰라서 찾아보다가 cout.setf(ios::fixed) (고정 소수점 출력) 구문을 써주고 cout.precision(n) n에 원하는 소수점 자릿수를 넣으면 된다는 것을 알게 되었습니다.

dmstj920 / 3월 1주차 / 3문제

---

myeongseo/1697_숨바꼭질.cpp
myeongseo/2606_바이러스.cpp
myeongseo/2667_단지번호붙이기.cpp

이번주는 bfs문제들을 풀었습니다!
[단지 번호 붙이기]
dfs랑 bfs 두 방식으로 모두 풀어봤습니다.
[바이러스]
bfs로 풀었고 인덱스 시작을 1부터 할 때 끝나는 범위를 항상 주의해야 해요. 아무 생각 없이 습관적으로 N으로 했다가 왜 틀렸나...했네요.
[숨바꼭질]
허허..메모리 초과도 나고, 컴파일 에러도 겪어보고 틀린 답까지..헤맴의 연속이었습니다..
원래 bfs를 재귀 함수로 작성했는데 메모리 초과로 재귀 없이 식 짜보기도 하고,
방문한 곳 중복 확인도 안 했었는데 확인하는 코드 새로 추가하고...bfs에 대해 많이 생각하고 고민하는 시간을 가졌습니다.
또, visit은 std::visit함수가 있으니 변수명 visit으로 쓰면 컴파일 에러납니다! 대신 visited로 쓰세요!!

myeongseo / 3월 1주차 / 3문제

---

125_validPalindrome.py
SeongHyun/125_validPalindrome.py
SeongHyun/334_reverseString.py
SeongHyun/937_ReorderData.py

**[LTC] ValidPalindrome / Easy / 10분]**
**[LTC] Reverse String / Easy / 5분]**
**[LTC] Reorder Data in Log Files / Easy / 50분]**

seonghyun koo / 3월 1주차 / 3문제

---

thkang727/1764_듣보잡.py
thkang727/1965_상자넣기.py
thkang727/7785_회사에 있는 사람.py

이번주는 문자열, DP, 자료구조 문제를 1문제씩 풀었습니다

thkang727 / 3월 1주차 / 3문제

---

seunggil/java/1865.java
seunggil/java/24525.java
seunggil/java/24526.java

[BOJ] 전화 돌리기 / 골드2 / 5시간
[https://www.acmicpc.net/problem/24526](https://www.acmicpc.net/problem/24526)
- 2022 성균관대학교 프로그래밍 경진대회 문제,
대회 때 풀지 못해 끝나고 다시 도전했으나 계속 틀림.
알고리즘 분류(위상정렬)을 보고 풀게 되었다. 위상정렬인걸 끝까지 못 알아내서 반쪽 짜리 성공.
[BOJ] 웜홀 / 골드3 / 51분
https://www.acmicpc.net/problem/24526
- 플로이드 워셜로 풀었는데 100%에서 시간 초과가 떠서 애먹은 문제.
- 정석 풀이는 벨만-포드 알고리즘인데 쓸 줄을 몰랐다.

seunggil / 3월 1주차 / 3문제

---

kimdonghun/[BOJ]1021_RotatingQueue.py
kimdonghun/[BOJ]1074_Z.py
kimdonghun/[BOJ]10830_MatrixSquare.py
kimdonghun/[BOJ]10866_Dequeue.py
kimdonghun/[BOJ]11401_BinomialCoefficient.py
kimdonghun/[BOJ]11444_Fibonacci6.py
kimdonghun/[BOJ]11866_JosephusProblem0.py
kimdonghun/[BOJ]1260_DFSAndBFS.py
kimdonghun/[BOJ]1629_Multiplication.py
kimdonghun/[BOJ]17289_RightUpperNum.py
kimdonghun/[BOJ]1780_TheNumberOfPaper.py
kimdonghun/[BOJ]18258_Queue2.py
kimdonghun/[BOJ]1874_StackSequence.py
kimdonghun/[BOJ]1966_PrinterQueue.py
kimdonghun/[BOJ]1992_QuadTree.py
kimdonghun/[BOJ]2164_Card2.py
kimdonghun/[BOJ]2480_ThreeDice.py
kimdonghun/[BOJ]2525_OvenClock.py
kimdonghun/[BOJ]2606_Virus.py
kimdonghun/[BOJ]2630_MakingColorPaper.py
kimdonghun/[BOJ]2667_ComplexNumbering.py
kimdonghun/[BOJ]2740_MatrixMultiplication.py
kimdonghun/[BOJ]4949_BalancedWorld.py
kimdonghun/[BOJ]5430_AC.py

kimdonghun / 3월 1주차 / 24개

---

lysuk96/Week11/11_BOJ_가장긴증가하는부분수열.py
lysuk96/Week11/11_BOJ_단어정렬.py
lysuk96/Week11/11_BOJ_동전0.py
lysuk96/Week11/11_BOJ_소수구하기.py
lysuk96/Week11/11_BOJ_소트인사이드.py
lysuk96/Week11/11_BOJ_알파벳.py
lysuk96/Week11/11_BOJ_차집합.py
lysuk96/Week11/1_바이러스.py
lysuk96/Week11/2_ATM.py
lysuk96/Week11/3_계단오르기.py
lysuk96/Week11/4_영화감독숌.py
lysuk96/Week11/5_쿼드트리.py
lysuk96/Week11/6_두수의합.py
lysuk96/Week12/12_BOJ_두용액.py
lysuk96/Week12/12_BOJ_전깃줄.py
lysuk96/Week12/12_BOJ_전설의JBNU.py
lysuk96/Week12/12_BOJ_중앙값구하기.py
lysuk96/Week12/12_BOJ_최단경로.py
lysuk96/Week12/12_BOJ_트리.py

기업 채용 본격적으로 시작중이네요. 모두들 화이팅입니다 :)

lysuk96 / 3월 2주차 / 19문제

---

seunggil/16637.cpp
seunggil/java/2342.java
seunggil/java/2467.java
seunggil/java/9466.java

[BOJ] Dance Dance Revolution / 골드3 / 3시간 18분
(https://www.acmicpc.net/problem/2342)
DFS + 백트래킹으로 시도했으나 중복 연산을 막지 못해 메모리 초과가 나서 DP로 다시 작성했다.
버튼 2개를 밟고 있을 때, 왼쪽 다리, 오른쪽 다리 구분은 필요 없다.
따라서 밟고 있는 버튼 상태를 비트로 나타내고, map<bit int, dp>를 통해 값을 구하는 매우 복잡한 방법을 사용했다.
사실 [왼쪽][오른쪽][index]로 dp를 표시하면 쉽게 풀리는 문제인데,
dp에 숙련되지 않아 너무 복잡하게 푼 것 같다.
[BOJ] 용액 / 골드5 / 1시간 6분
(https://www.acmicpc.net/problem/2467)
정보올림피아드 초등부 문제로, 이분탐색을 이용하는 간단한 문제지만,
수학머리가 나쁜지 저 방법 대신 set을 사용해 한참 걸려 풀었다...

seunggil / 3월 2주차 / 4문제

---

thkang727/1254_팰린드롬 만들기.py
thkang727/2331_반복수열.py
thkang727/9461_파도반 수열.py

이번주는 bfs/dfs, 문자열, 수학 관련 문제로 각 1문제씩 풀이했습니다. 문자열 문제에서 간단하다 생각했었는데, 같은 문자열을 찾는데 시간이 걸렸습니다.

thkang727 / 3월 2주차 / 3문제

---

dmstj920/1065_한수.cpp
dmstj920/1181_단어정렬.cpp
dmstj920/13458_시험감독.cpp
dmstj920/9012_괄호.cpp

알고리즘 분류 : [1056] 브루트포스 / [1181] 문자열 ,정렬 / [13458] 수학,  사칙연산 / [9012] 자료구조, 문자열, 스택
**[13458] 시험 감독**
- 브론즈문제인데 정답률이 낮아서 호기심에 풀어봤습니다. 처음에 자꾸 결과값이 안나와서 왜지? 하다가 검색 해보니 결과값의 자료형을 int로 설정해놔서 그렇다는 걸 알게 되었습니다. 항상 문제를 풀 때 숫자라고 하면 int를 습관적으로 썼었는데 이제 범위를 체크 해보고 그에 맞춰서 써야겠다고 생각했습니다.
**[9012] 괄호**
- 알고리즘 분류를 적으려고 보다가 스택 문제라는 걸 알게 되었는데 저는 스택으로 풀지 않아서 다음에 스택으로도 한번 풀어보려고 합니다!

dmstj920 / 3월 2주차 / 4문제

---

HyeGyoungPark/10814_sortAgesort.cpp
HyeGyoungPark/11656_sortsuffix.py
HyeGyoungPark/20291_sortFile.py

[알고리즘 분류]
나이순 정렬[10814], : 정렬
파일 정리[20291], 접미사 배열[11656] : 정렬, 문자열
나이순 정렬[10814] 은 사실 이름도 알파벳순으로 정리하는가? 싶어서 pair에 string 넣으면 같이 해주는지 알아보고 싶어서 했는데 문제가 이름순은 정렬하지 않더라구요! 그래서 약간 아쉬웠지만 pair를 좀 더 잘 쓰게 되어서 기분이 좋았습니다.
파일 정리[20291], 접미사 배열[11656] 은 문자열 정렬을 제가 상당히 귀찮고 싫어하더라구요. 그래서 극복해보고자 풀었습니다. 파일 정리는 처음에 그냥 리스트로 했더니 시간 초과가 나서 조금 더 오래 걸렸습니다. 문자열 관련 문제는 파이썬으로만 자꾸 풀이가 생각되어서 파이썬으로 풀었습니다!

HyeGyoungPark / 3월 2주차 / 3문제

---

jaewon/94_BTInorderTraversal.cpp

- https://leetcode.com/problems/binary-tree-inorder-traversal/
- 트리 순회중에 중위 순회를 하는 문제. 흔히 사용하는 재귀 호출 방법과 반복문 방법을 사용했는데 반복문으로 풀이를 할 때는 stack을 이용했다. 
- 트리 순회 이름이 자꾸 헷갈린다. 전위순회 pre, 중위순회 in, 후위순회post
- 전위순회는 self > left child > right child
- 중위순회는 left child > self > right child
- 후위순회는 left child > right child > self

Jaewon / 3월 3주차 / 1문제

---

seunggil/16637.cpp
seunggil/java/1374.java
seunggil/java/14600.java
seunggil/java/17281.java
seunggil/java/2239.java

[BOJ] 사다리조작 / 골드4 / 3시간 이상
https://www.acmicpc.net/problem/15684
- 문제에 적힌 한 줄 놓쳐서 3시간동안 헛고생했다
[BOJ] ⚾/ 골드4 / 2시간 5분
https://www.acmicpc.net/problem/17281
- 구현 정확도 낮음 + 내 어림짐작으로 문제에 나오지도 않은 조건으로 실제 야구 룰을  추가 ⇒ 오류 찾느라 시간이 너무 오래 걸렸다. 
[BOJ] 같은 수로 만들기 / 골드4 / 2시간 7분
https://www.acmicpc.net/problem/2374
- 자바는 List에 새 원소를 추가하면 기존의 iterator가 사용할 수 없어진다. C++ 같은 편리한 iterator 기능이 없는 것이 아쉽다.

seunggil / 3월 3주차 / 5문제

---

dmstj920/11656_접미사배열.cpp
dmstj920/2435_기상청인턴신현수.cpp
dmstj920/5635_생일.cpp

알고리즘 분류 : [11656] 문자열, 정렬 / [5635] 구현, 정렬 / [2435] 브루트포스, 누적 합
**[2435] 기상청 인턴 신현수**
- 온도가 음수만 나올 경우를 생각하지 못하고 max의 초기값을 0으로 시작했다가 반례를 찾아보고 알게 되었습니다.

dmstj920 / 3월 3주차 / 3문제

---

namhee/nh077_boj02558.java

여러 문제 도전했는데 성과가 없었습니다.
유일하게 푼 문제가 입출력 문제네요😂
Scanner, BufferedReader 입출력에 익숙해지기 위해 풀어본 문제입니다!
덕분에 어떻게 사용해야 할지 감이 좀 온 것 같아요!
둘의 성능 차이가 인상 깊었습니다😄
아래는 문제 풀면서 쓴 주석을 옮겨 쓴 내용입니다!
[A+B - 2 문제 성능 분석]
Scanner 썼을 때 : Memory 17.728MB, 시간 204ms
BufferedReader 썼을 때 : Memory 14.172MB, 시간 124ms
간단한 A + B 출력에도 꽤 많은 차이가 난다!
테스트 케이스 몇 갠지 모르는 게 좀 아쉬웠다.

namhee / 3월 3주차 / 1문제

---

shasuri/12th_week/1927_min_heap.cpp
shasuri/12th_week/1927_min_heap_array.cpp
shasuri/12th_week/1927_min_heap_linked_list.cpp

늦어서 죄송합니다...!!
한문제를 두 가지 방식으로 풀어보았습니다!
의도치 않게요...ㅠㅠㅠ
ps. 역량테스트 너무 까다로워용...

shasuri / 3월 3주차 / 1문제

---

thkang727/1002_터렛.py
thkang727/1120_문자열.py
thkang727/11653_소인수분해.py
thkang727/1676_팩토리얼0의개수.py
thkang727/17413_단어 뒤집기2
thkang727/슈퍼 마리오.py

이번주는 3문제 풀이를 하였습니다. 브루트포스 1문제(슈퍼 마리오), 문자열 2문제(문자열, 단어 뒤집기 2)를 풀이했습니다.

thkang727 / 3월 3,4주차 / 6문제(3,3)

---

Codesik/BOJ/Bruth_Force/BOJ_1969_DNA.py
Codesik/BOJ/String/BOJ_17609_회문.py
Codesik/BOJ/String/BOJ_9342_염색체.py
Codesik/BOJ/Two_Pointer/BOJ_20922_겹치는건싫어.py
Codesik/Programmers/Implementation/PGS_나머지한점.py

Codesik / 3월 4주차 / 5문제

---

jaewon/152_maxProductSubarray.cpp
jaewon/153_FindMinimumRotatedArray.cpp
jaewon/238_productExceptSelf.cpp
jaewon/33_searchTargetRotatedArray.cpp

[LTC] 152번 Maximum Product Subarray
- case별로 분기를 해주는게 어려웠던 문제. 이중배열을 사용한 DP로 풀수있었다.
- 이중벡터를 사용하면 메모리를 더 절약할 수 있었을 것 같은데 여전히 이중벡터사용에 익숙하지 않은 것 같다.
[LTC] 238번 Product of Array Except Self
- 시간 복잡도 측면에서 쉽지 않았던 문제
- 각 곱셈과 덧셈사이의 규칙을 발견해서 두개를 이용하는 식으로 풀었던 수학 퀴즈같던 문제
[LTC] Find Minimum in Rotated Sorted Array / Search in Rotated Sorted Array
- low와 high, mid를 이용한 이분탐색으로 풀었다.
- search는 target을 더 넣은 문제인데 이 문제는 경우별로 구간을 나누어서 풀었다.
- 근데 테스트케이스에서 틀릴 때마다 수정했던 문제라 마음에 드는 풀이는 아니다.

Jaewon / 3월 4주차 / 4문제

---

HyeGyoungPark/1764_SortStringlistenseeNO.py
HyeGyoungPark/1940_sortJumong.py

[알고리즘 분류]
듣보잡_ 1764 : 정렬, 문자열
주몽_1940 : 정렬
문자열은 파이썬으로 접근하는게 익숙해서 이번에도 파이썬으로 풀어 보았습니다. 그런데 파이썬에 있는 a in list 라던가 a not in lisr 이런 조건문의 조건은 O(n^2)라는 것 같더라구요. 그래서 계속 시간 초과가 나서 이번에도 딕셔너리를 사용했습니다. 딕셔너리가 문자열에서는 확실히 중요한 것 같고, 그래서 데이터 쪽에서 파이썬을 주로 쓰는가 싶기도 하고(물론 이 이유는 아닐 것 같습니다...) 모쪼록.. C나 C++에서의 문자열 다루는 것도 익숙해지기 위해 노력 해야겠습니다.
주몽은 정렬해서 어떻게 하면 될 것 같다는게 생각이 나길래 바로 해 보았습니다. 생각보다 중간중간 오류가 나서 조금 시간이 걸렸지만, 잘 되었습니다.
이번주는 아쉽게 2개로 마무리 할 듯 싶어요ㅜㅡㅜ 다음주에는 4개를 풀고 그 다음주에도 4개, 그 다음주에도 4개 해서 지난주에 못 푼 것까지 풀고 싶네요!

HyeGyoungPark / 3월 4주차 / 2문제

---

namhee/nh078_boj10953.java
namhee/nh079_boj14503.java

3문제 풀려다 PR 늦어버렸네요 ㅠㅠ
java 입출력에 익숙해지기 위한 문제랑 코테 대비 구현 문제 풀었습니다!
별다르게 특별한 알고리즘은 없습니다.

namhee / 3월 4주차 / 2문제

---

myeongseo/11726_2xn타일링.cpp
myeongseo/1463_1로만들기.cpp
myeongseo/9095_123더하기.cpp

이번주는 dp문제들을 찾아서 풀어봤습니다.
확실히 dp문제임을 인식하고 그쪽으로 접근 방법을 생각하니 훨씬 빨리 답이 생각이 나네요.
[1로 만들기]
보통 dp에서는 식에 집중을 하는데 초기 조건도 잘 생각해줘야 같아요! 
초기 조건에서 dp[1]을 아무 생각 없이 1로 생각했는데 나중에 보니 생각해보니 0이었습니다...
[1,2,3 더하기]
중간에 solve 함수 작성 부분에서 변수를 잘못 사용해서 조금 헤맸습니다. 
[2xn 타일링]
처음엔 왜 굳이 10007의 나머지로 답을 계산할까 했는데 오버플로우를 방지하기 위함이었네요.

myeongseo / 4월 1주차 / 3문제

---

Ernstjunger-1914/[BOJ]N-Queen.cpp
Ernstjunger-1914/[BOJ]약수.cpp
Ernstjunger-1914/[BOJ]연산자 끼워넣기.cpp

하나는 일요일에 commit했는데 그때 PR 이미 받으셔서 올라간 거 같네요.

Ernstjunger-1914 / 4월 1주차 / 4문제

---

jaewon/1143_LCS.cpp
jaewon/139_wordBreak.cpp
jaewon/15_threesum.cpp
jaewon/377_combinationSum.cpp

[LTC] 3Sum
- 단순히 3중 반복문으로 풀려고하거나 2중반복문 + hash로 풀려고하면 계속 시간초과만 난다.
- 2Sum은 반복문 + hash로 풀렸기 때문에 해당 문제에서 target을 -num[i]로 두고 풀면 풀릴 줄 알았는데 아니었다.
- discuss에 있는 front/back을 이용한 투포인터 풀이를 참고했다(거의 코드가 같아졌다.)
- 투포인터 풀이를 하더라도 while(){ptr ++ }부분을 신경써주지 않으면 그대로 시간초과가 나는 문제였다. 
- 그냥 새로운 풀이를 알았다는 것으로 넘어갈 수 있는 문제라고 생각한다.

Jaewon / 3월 5주차 / 진행중

---

thkang727/14916_거스름돈.cpp
thkang727/2609_최대공약수와 최소공배수.cpp

이번주는 수학 주제에 대해 2문제 구현을 했습니다. 2문제 모두 실버 5 난이도로, 경우의 수만 잘 따지고 하면 구현은 쉬웠던 문제입니다. 다음주에는 이번주 못한 1문제를 포함하여 4문제 이상 하려합니다!

thkang727 / 4월 1주차 / 2문제

---

jaewon/198_houseRobber.cpp
jaewon/213_houseRobber2.cpp
jaewon/91_decodeWays.cpp

[House Robber] 
- DP문제. 계단 문제와 비슷하다.
- https://leetcode.com/problems/house-robber/
[House Robber]
- 배열이 원형이라고 가정하고 푸는 문제. 
- 조건을 더 넣어주면 된다.
[Decode ways]
- 어려웠다. bfs로 풀려고했는데 dp를 저장을 못해서 그렇게는 풀 수 없었다.
- 결국 내가 제일 못하는(어려워하는) dfs로 풀수밖에 없었다.
- 내가 제일 못하는 조합 dfs + 문자열 이여서 너무 어려웠다 ㅠㅠ

Jaewon / 4월 2주차 / 3문제

---

namhee/nh080_boj01254.java
namhee/nh081_boj04949.java
namhee/nh082_boj14500.java
namhee/nh083_boj10250.java
namhee/nh084_boj01259.java

Java 문자열 메소드에 익숙해지기 위해서 문자열 문제 위주로 풀었습니다!
삼성 A형 시험에 대비해 테트로미노라는 문제를 풀었습니다.
일단 완전 탐색으로 풀 수 있는지를 먼저 풀 수 있는지 체크하고, 그 다음 중복을 줄이는 식으로 풀이를 접근하면 좋다고 해서 연습하고 있는데 그 말의 의미를 알 수 있었던 문제였습니다.

namhee / 4월 2주차 / 5문제

---

Codesik/BOJ/Graph_Traversal/BOJ_2667_단지번호붙이기.py

https://www.acmicpc.net/problem/2667

Codesik / 4월 2주차 / 1문제

---

jaewon/2848_algospot.cpp
jaewon/417_ocean.cpp

알고스팟어 제 풀이는 틀려서 죽을뻔했네요 진짜 이유를 아직도 모르겠어요

Jaewon / 4월 3주차 / 2문제

---

thkang727/1920_수찾기

이번주는 1문제(자료구조)풀이 했습니다. 시간 초과로 인해 시간이 꽤 소요되었는데, 시간을 빠르게 하려고 했던 list 의 remove 함수로 인해 시간 초과 된 것을 알았습니다. remove 함수를 그냥 코드 한 줄로만 안일하게 생각했었습니다.
다음주까지는 1문제만 올리겠습니다..

thkang727 / 4월 3 주차 / 1문제

---

seunggil/java/10473.java
seunggil/java/11401.java
seunggil/java/1708.java
seunggil/java/4181.java
seunggil/java/5719.java

[BOJ] 볼록 껍질 / 플래5 / 6시간 30분
- Graham Scan 알고리즘을 사용하는 문제, 외적을 통해 방향을 확인하는 문제.
[BOJ] Convex Hull / 플래5 / 60시간.
- 볼록 껍질과 동일한 문제가 살짝 바뀌니 끔찍한 문제가 되었다. 
- 벡터의 외적, 내적 + 정렬
(추가)Graham Scan 대신 Monotone Chain도 있다고 한다..
[BOJ] 거의 최단 경로 / 플래5 / 5시간
- 문제는 다익스트라만 알면 누구나 이해할 수 있고, 사용하는 알고리즘도 다익스트라 + bfs만 써서 푸는 문제이다.
- 하지만 다익스트라를 정확하게 이해하고 않으면 난이도가 매우 어려워진다.

seunggil / 4월 3 주차 / 5문제

---

thkang727/1138_한 줄로 서기.cpp
thkang727/2960_에라토스테네스의 체.py
thkang727/4949_균형잡힌세상.cpp

이번주도 1문제 올립니다. 다음주 시험 끝나면 곱으로 채워놓겠습니다 ㅎㅎ
이번주도 자료구조- 스택을 사용한 문제를 풀이했습니다.
c++의 STACK 라이브러리 사용이 미숙하여 조금 지체되었으나 다소 쉽게 풀이했습니다!

thkang727 /4월 4주차 / 1문제

---

Codesik/Programmers/Implementation/PGS_로또의최고순위와최저순위.py
Codesik/Programmers/Implementation/PGS_신고결과받기.py

https://programmers.co.kr/learn/courses/30/lessons/77484

Codesik / 4월 5주차 / 진행중

---

lcy8047/1167_트리의지름.cpp
lcy8047/2407_조합.cpp

저번 pr에 이번주에 풀었던 문제 1개가 같이 들어가 있었네요 ㅜㅜ

lcy8047 / 4월 5주차 / 3문제 

---

myeongseo/1059번_좋은구간.cpp
myeongseo/1072_게임.cpp

이번주는 골드만 풀려고했는데 제가 처음 선택했던 문제를 풀다가 막혀서 결국 포기하고 실버로 방향을 바꿨습니다...ㅠ..
아직은 실버로 더 연습을 해야 할 거 같네요
[좋은 구간]
아이디어가 금방 생각나서 쉽다라고 생각했는데 예제를 넣어보면서 제가 놓친 고려 사항이 있는 것을 알게 되었네요. 
처음부터 완벽하게 설계 못하고 예제를 돌리면서 빠진 부분을 채워 넣는 습관을 고쳐야 하는데 생각보다 잘 되지 않네요. 
[게임]
X와 Y를 1씩 더해가면 답을 찾는 방식으로 구현을 하니까 시간초과가 나더라구요(당연한 사실인데 처음 설계할 때 고려를 못했네요)
그래서 이분탐색 방법으로 바꿔서 문제를 해결했습니다.

myeongseo / 4월 5주차 / 2문제

---

Ernstjunger-1914/[BOJ]링.cpp
Ernstjunger-1914/[BOJ]신나는 함수 실행.cpp
Ernstjunger-1914/[BOJ]파이프 옮기기 1.cpp

중간에 commit 메세지 잘못 넣은게 있네요.
이번 주 총 3문제입니다.

Ernstjunger-1914 / 4월 5주차 / 3문제

---

shasuri/19th_week/2021_kakao_intern_1.py
shasuri/19th_week/2021_kakao_intern_2.cpp
shasuri/19th_week/2_test.cpp

shasuri / 5월 1주차 / 2문제

---

thkang727/1012_유기농배추.py
thkang727/10973_이전순열.py
thkang727/1388_바닥장식.py
thkang727/2504_괄호의값.py
thkang727/4963_섬의개수.py
thkang727/8911_거북이.py

4문제 모두 구현 태그에 대해 해보았습니다.
한 문제는 괄호의 값으로 스택을 이용하여 푸는 문제입니다.
한 문제는 숫자 정사각형 문제로 n*m 배열을 입력받아 꼭짓점이 같은 숫자값을 지닌 값을 입력받는 문제입니다.
한 문제는 숫자의 순열을 입력 받았을 때 숫자의 이전 순열을 출력합니다.
나머지 한 문제는 임의의 좌표계를 두고, 거북이를 앞뒤, 좌우 턴을 이용하여 이동할때, 이동을 마친 후 좌표를 출력하는 문제입니다.
5주차에는 그래프 개념에 익숙해지기 위해 그래프 관련 문제들을 풀었습니다.
바닥장식 문제는 연속된 -, | 의 개수를 세는 문제로, n*n 배열에서 2중 포문으로 접근하되, 갯수에 포함된 것이 아니면 dfs 로 접근했습니다.

thkang727 / 5월 2주차 ~4주차 / 4문제(ing)

---

myeongseo/1075_나누기.cpp
myeongseo/1080_행렬.cpp
myeongseo/1083_소트.cpp

[행렬]
그리디 방식으로 풀었습니다.
위에서부터 아래로 내려오면서 A와 B의 차이가 있으면 3x3크기의 행렬을 뒤집어 주었습니다.
[소트]
사전순으로 가장 뒷서도록 출력하라길래 다른 곳의 순서를 바꾸는 것보다 앞에서 부터 차례대로 최대한 크게 만들면 좋다고 생각했습니다. 이 문제도 그리디로 풀었습니다!

myeongseo / 5월 3주차 / 3문제

---

Ernstjunger-1914/[BOJ]1의 개수 세기.cpp
Ernstjunger-1914/[BOJ]문자열 집합.cpp
Ernstjunger-1914/[BOJ]서로 다른 부분 문자열의 개수.cpp
Ernstjunger-1914/[BOJ]히스토그램에서 가장 큰 직사각형.cpp

5월 3주차 문제는 며칠 전에 PR 하셔서 같이 올라갔네요.

Ernstjunger-1914 / 5월 4주차 / 4문제

---

thkang727/11724_연결 요소의 개수.py

4주차에는 그래프 개념에 익숙해지기 위해 그래프 관련 문제들을 풀었습니다.
유기농 배추, 섬의 개수 문제는 임의의 2차원 배열에서 해당 좌표를 넣어서 dfs 탐색을 이용하여 풀이했습니다.
연결 요소의 개수 문제는 리스트에서 각 노드에서 가리키는 타 노드를 넣어 준 다음, 탐색하는 방식으로 dfs탐색을 이용하여 풀이했습니다.

thkang727 / 5월 4주차 ~ / 3문제

---

bumwoo/12973.py
bumwoo/1461.py
bumwoo/17070.py
bumwoo/1781.py
bumwoo/77485.py

git에 다른 계정이 연결되어 있어서 commit이 많아졌습니다 죄송합니다
1번 문제는 이중 for문, 포인터를 이용해서 풀었으나 실패해서 stack에서 힌트를 얻어서 풀었습니다.
2번 문제는 python deepcopy가 시간이 많이 소요되는걸 깨닫고 list slicing으로 풀었습니다.

beomukim / 5월 4주차 / 2문제

---

thkang727/9012_괄호.py

6월 1주차는 문자열 태그에 대해 1문제 문제풀이를 했습니다.
괄호 배열이 올바른지 찾는 문제로, for문을 돌려, 매 턴 끝날때 마다
'여는 괄호'와 '닫는 괄호'의 수를 비교하여 '닫는 괄호'의 수가 많으면 'NO' 출력 후 다음 괄호 배열 입력을 받게했습니다.

thkang727 / 6월 1주차 / 1문제

---

thkang727/11501_주식.py
thkang727/18310_안테나.py
thkang727/19941_햄버거분배.py

이번주는 그리디 알고리즘 3문제에 대한 문제풀이를 진행했습니다

thkang727 / 6월 3주차 / 3문제

---

jaewon/cp_heapsort.cpp
jaewon/cp_mergesort.cpp
jaewon/cp_participant.cpp
jaewon/cp_segmenttree.cpp
jaewon/cp_shoppingmall.cpp
jaewon/cp_sumzero.cpp
jaewon/cp_trieNumber.cpp
jaewon/cp_trieString.cpp
jaewon/cp_unionfind.cpp

하루에 한 개씩은 푸는 것 같습니다.
코드 최적화를 위해 공부하고있습니다만 아직도 어렵네요

Jaewon / 6월 4주차 / 9개

---

sangbeomheo/PGS_42576_완주하지-못한-선수.js
sangbeomheo/PGS_42746_가장-큰-수.js
sangbeomheo/PGS_42747_H-index.js
sangbeomheo/PGS_42748_K번째수.js

안녕하세요 :)
처음 PR 날려봅니다. 2달 전에 시작하려고 문제 푼 걸 이제 날리네요. 잘 부탁드립니다!

Sangbeomheo / 6월 4주차 / 4문제

---

SeongHyun/104_maxDepth.py
SeongHyun/122_sellStock2.py
SeongHyun/406_queueReconstruction.py

[LTC] Maximum Depth of Binary Tree / Easy / 30분]
:트리 깊이 조사, bfs로 순회하면서 depth증가
[LTC] Best Time to Buy and Sell Stock II / Medium / 10분]
:다음 가격이 높을 때 이익으로 추가, 그리디 알고리즘
[LTC] Queue Reconstruction by Height / medium / 40분]
:정렬 후 키가 작은 사람부터 배치

SeongHyun / 6월4주차 / 3문제

---

Codesik/Programmers/Graph_Traversal/PGS_배달.py

https://programmers.co.kr/learn/courses/30/lessons/12978

Codesik / 6월 5주차 / 1문제

---

jaewon/14725_anthill.cpp

[BOJ] 14725번 개미굴 골드3
https://www.acmicpc.net/problem/14725
- 트라이 연습을 위해 사용. sort하는 과정이나 인덱싱하는 과정 다시 알아보고싶다. 
- 트라이 치고 너무 더럽게 풀었다.

Jaewon / 7월 1주차 / 1문제 

---

2021_kakao_codingtest_2.py
SeongHyun/2021_kakao_codingtest_1.py
SeongHyun/2022_kakao_codingtest_1.py
SeongHyun/2022_kakao_codingtest_2.py

**[PGS] 신고 결과 받기 / lv.1 / 20분**
단순 구현, string, map
**[PGS] k진수에서 소수개수 구하기 / lv.2 / 40분**
단순 구현, 분할정복
소수인지 판별할때 연산량을 줄이려고 range(2, 제곱근의 올림)의 범위로 검사했는데 제곱근이 딱 떨어질때를 포함하지 않는 문제가 발생하게 되어 제곱근의 반올림+1까지 검사하도록 한 후에 모든 케이스가 통과되었습니다.
**[PGS] 신규 아이디 추천 / lv.1 / 20분**
단순구현, string
문자열 필터링 문제입니다. 정규표현식을 적극 활용하였습니다.
**[PGS] 메뉴 리뉴얼 / lv.2 / 60분**
단순구현, 
defaultdict를 이용해서 없는 값으로 접근할 때 기본값을 설정할수 있는 걸 알게되었습니다.  요소의 조합을 이용해야해서 itertools모듈을 사용하였는데, combinations함수는 입력되는 리스트의 순서에 따라 결과가 달라지는데 이점을 간과하여 생긴 문제를 발견하기까지 시간이 조금 소모 되었습니다.

Seonghyun / 7월 1주차 / 4문제

---

sangbeomheo/PGS_12909_올바른-괄호.js
sangbeomheo/PGS_42579_베스트앨범.js
sangbeomheo/PGS_91086_배상-비용-최소화-실습.js
sangbeomheo/PGS_92334_신고결과받기.js

[PGS] 올바른 괄호 / 레벨2 / 50분
- stack
[PGS] 베스트앨범 / 레벨2 / 2시간
- hash
[PGS] 배상 비용 최소화 실습 / 레벨2 / 2시간
- 우선순위 큐
[PGS] 신고 결과 받기 / 레벨1 / 50분
- 단순구현

Sangbeomheo / 7월 1주차 / 4문제

---

ga-ng/11047_coin0.py
ga-ng/11399_ATM.py
ga-ng/13305_gasStation.py
ga-ng/1541_missingBracket.py

ga-ng / 7월 1주차 / 4문제

---

eodudrepublic/8979_올림픽.py

[BOJ] 올림픽 / 실버5 / 20분
알고리즘 분류 : 구현, 정렬

eodudrepublic / 7월 2주차 / 1문제

---

thkang727/2785_체인.py

그리디 알고리즘에 대한 문제풀이를 했습니다. 체인문제의 경우 array를 입력받아 array를 정렬하여 가장 작은 값을 찾습니다. 가장 작은 값을 체인으로 사용하여 연결해줍니다. 체인으로 사용하여 연결을 해주고, 연결을 마치고 남으면 그 수만큼 더해줍니다.
이번주 문제를 하나를 행렬을 풀이하려했으나, 막혀서 다음주에 다시 풀이하겠습니다.

thkang727 / 7월 2주차 / 1문제

---

gardenia0917/JS/22.07.09_01_Two Sum

오늘 시작합니다.
첫 시작이라서 제일 쉬운 문제로 시작합니다.

gardenia0917 / 7월 2주차 / 1문제

---

NadudAn/week1/PGS_12928.java
NadudAn/week1/PGS_12935.java
NadudAn/week1/PGS_12937.java

처음 시작하는거라 간단한 문제들을 풀어봤습니다
약수 합 더하는 문제와 홀짝 구하기, 배열에서 최소값 제거하기 등..
특히 최소값 제거하는 문제가 Sort로 풀었다가 for문으로 바꾼거라 좀 오래 걸렸던 것 같습니다.

NadudAn / 7월 2주차 / 3문제

---

NadudAn/week2/PGS_42840.java
NadudAn/week2/PGS_82612.java
NadudAn/week2/PGS_86051.java

- 없는 숫자 더하기
- BinarySearch를 이용하여 만약 0보다 작은 경우 수를 더하도록 하였습니다.
- 부족한 금액 더하기
- for문을 이용하여 풀었습니다.
- 모의고사
- 인덱스값을 학생 답안의 개수로 나눈 나머지값을 이용하여 맞는지 틀린지 카운트하고 비교하였습니다. ArrayList를 이용하여 리턴할 때 int형 배열로 바꿔주었습니다.

NadudAn / 7월 3주차 / 3문제

---

HyeGyoungPark/SlidingwindowDPHoney.cpp

[알고리즘 분류]
12847_꿀 아르바이트 : 슬라이딩 윈도우, DP
12847_꿀 아르바이트의 경우 1학기에 데이터 통신 강의에서 슬라이딩 윈도우 라는 것을 본 것도 있고, 저번에 푼 문제 중에도 있었어서 더 풀어보고 싶어 풀게 되었습니다. 해당 문제를 DP로 접근하지 않고 처음 풀었더니 시간초과가 나서(2중 for문) 해당 문제 질문 게시판을 보던 중, DP로 접근하면 해결된다는 글을 보고 방식을 바꾸었더니 통과 되었습니다! 그거랑 변수의 범위를 잘 보자는 마음을 다시 한 번 깨닫게 되는 문제였습니다..^^..... long long...........^^................

HyeGyoung / 7월 3주차 / 1문제

---

thkang727/1213_펠린드롬 만들기.py
thkang727/17103_골드바흐 파티션.py
thkang727/4889_안정적인 문자열.py

이번주는 3문제를 풀었습니다.
1문제는 수학 태그에 대해, 2문제는 문자열 태그에 대해 풀이했습니다.
수학 태그의 골드바흐 파티션 문제가 어려웠습니다.
매 케이스 마다 소수 수를 구하는 것은 비효율 적이고,
100만의 소수를 미리 다 구하고 하는 것도 비효율적입니다.
그렇기에 입력 케이스에서 가장 큰 값을 기준으로 소수의 수를 구했습니다

thkang727 / 7월 3주차 / 3문제

---

jaewon/1717_groups.cpp
jaewon/1976_travel.cpp
jaewon/4195_friends.cpp

1. [BOJ] 집합의 표현 / 골드4 / 20분  - https://www.acmicpc.net/problem/1717
2. [BOJ] 여행가자 / 골드4 / 1시간 - https://www.acmicpc.net/problem/1976
3. [BOJ] 친구 네트워크 /  골드2 / 1시간 - https://www.acmicpc.net/problem/4195
- 위 세 문제는 Union-Find 연습

Jaewon / 7월 5주차 / 3문제

---

ga-ng/10773_zero.py
ga-ng/10816_numCard2.py
ga-ng/10828_stack.py
ga-ng/10844_eazyStairs.py
ga-ng/11053_LongestSequence.py
ga-ng/11054_longestBitonic.py
ga-ng/11279_maxHeap.py
ga-ng/11286_absHeap.py
ga-ng/1149_rgbDistance.py
ga-ng/12015_theMostlongestNum.py
ga-ng/12865_ordinaryBackpack.py
ga-ng/1300_kthNumber.py
ga-ng/1463_makeToOne.py
ga-ng/1654_cutLAN.py
ga-ng/1655_tellMid.py
ga-ng/17298_NGE.py
ga-ng/1904_tile1.py
ga-ng/1912_sequentialSum.py
ga-ng/1920_findingNum.py
ga-ng/1927_minHeap.py
ga-ng/1932_integerTriangle.py
ga-ng/2110_installRouter.py
ga-ng/2156_drinkGrapeJuice.py
ga-ng/24416_fibNum.py
ga-ng/2565_electricCord.py
ga-ng/2579_climingStair.py
ga-ng/2805_cuttingWood.py
ga-ng/9184_pleasureFunction.py
ga-ng/9251_LCS.py
ga-ng/9461_padoban.py

Ga-ng / 8월 1주차 / 23문제

---

thkang727/1011_Fly me to the Alpha Centauri.py
thkang727/11478_서로 다른 부분 문자열의 개수.py
thkang727/16922_로마숫자만들기.py
thkang727/9613_GCD합.py

이번주 알고리즘 스터디는 수학 태그에 대해 3문제 풀이했습니다.
실버 난이도와 더불어 골드 난이도에 대해서도 문제 풀이해보았는데,
앞으로의 스터디에서도 해보려 합니다!

thkang727 / 8월 1주차 / 3문제

---

sangbeomheo/PGS_17681_비밀지도.js
sangbeomheo/PGS_17682_다트-게임.js
sangbeomheo/PGS_42586_기능개발.js
sangbeomheo/PGS_42862_체육복.js
sangbeomheo/PGS_60057_문자열-압축.js
sangbeomheo/PGS_77884_약수의-개수와-덧셈.js

제가 실수로 머지 전에 계속 푸시를 했네요. 괜찮으시다면 전부 머지 부탁드립니다.
이번주는 수~금 까지 푼 내용을 다음 PR로 날리겠습니다.

Sangbeomheo / 8월 1주차 / 3문제

---

Jeonghak/Programmers/k진수에서소수개수구하기.cpp
Jeonghak/Programmers/양과늑대.cpp
Jeonghak/Programmers/양궁대회.cpp

이번 주에 푼 5문제가 저번주 pr에 push 되었습니다😃

jeonghak / 8월 2주차 / 7문제

---

suyeonsu/BFS_22869.py
suyeonsu/BFS_게임맵최단거리.py
suyeonsu/BinarySearch_19637.py
suyeonsu/BruteForce_14502.py
suyeonsu/BruteForce_2422.py
suyeonsu/BruteForce_전력망을둘로나누기.py
suyeonsu/BruteForce_카펫.py
suyeonsu/BruteForce_피로도.py
suyeonsu/DFS_네트워크.py
suyeonsu/DP_1106.py
suyeonsu/DP_1535.py
suyeonsu/DP_7579.py
suyeonsu/DataStructure(Set)_방문길이.py
suyeonsu/Hash_전화번호목록.py
suyeonsu/MST(Prim)_1197.py
suyeonsu/MST(Prim)_14621.py
suyeonsu/MST(Prim)_1922.py
suyeonsu/MST_9372.py
suyeonsu/Math_위장.py

최소 스패닝 트리, DFS, BFS, 완전탐색, 냅색 알고리즘
- [14502. 연구소](https://www.acmicpc.net/problem/14502) 완전탐색, DFS
- [2422. 한윤정이 이탈리아에 가서 아이스크림을 사먹는데](https://www.acmicpc.net/problem/2422) 완전탐색
- [1922. 네트워크 연결](https://www.acmicpc.net/problem/1922) 그래프, MST
- MST 구현 방법: Kruskal 알고리즘, Prim 알고리즘
- [9372. 상근이의 여행](https://www.acmicpc.net/problem/9372) 그래프, MST
- 최소 스패닝 트리의 간선 개수 = '노드 수 - 1'
- [1197. 최소 스패닝 트리](https://www.acmicpc.net/problem/1197) 그래프, MST
- [14621. 나만 안되는 연애](https://www.acmicpc.net/problem/14621) 그래프, MST
- [22869. 징검다리 건너기 (small)](https://www.acmicpc.net/problem/22869) 그래프, BFS
- 탐색 과정에서 불필요한(이미 수행한) 부분을 탐색하지 않도록 할 것
- [1106. 호텔](https://www.acmicpc.net/problem/1106) 배낭문제(0-1 knapsack), DP
- 문제의 '적어도'라는 조건에 유의
- [방문길이](https://school.programmers.co.kr/learn/courses/30/lessons/49994)
- …

suyeonsu / 8월 3주차 / 15문제

---

thkang727/11656_접미사 배열.py
thkang727/14425_문자열집합.py

thkang727 / 9월 2주차 / 3문제

---

gusah009/Java/[BOJ]주사위 세개.java
gusah009/Java/[PGS]3차_압축.java
gusah009/Java/[PGS]H-index.java
gusah009/Java/[PGS]_최적의_행렬_곱셈.java
gusah009/Java/[PGS]가장 큰 수.java
gusah009/Java/[PGS]괄호 회전하기.java
gusah009/Java/[PGS]땅따먹기.java
gusah009/Java/[PGS]오픈채팅방.java
gusah009/Java/[PGS]주식가격.java

gusah009 / 9월 3주차 / 9문제

---

namhee/nh096_boj1101.java
namhee/nh097_boj2232.java
namhee/nh098_boj11719.java

천천히 쉬운 문제라도 한 개씩 풀려고 하는 중이에요🙂
알고리즘은 한번 안하기 시작하면 정말 시작하기가 힘든 것 같아요😅

namhee / 9월 4주차 / 3문제

---

llddang/1074_Z(2).cpp
llddang/23246_SportClimbingCombined.cpp
llddang/23247_Ten.cpp
llddang/24460_특별상이라도받고싶어.cpp
llddang/4779_칸토어집합.cpp
llddang/6576_쿼드트리.cpp
llddang/6580_쿼드 트리
llddang/[ETC]BalanceScale.cpp
llddang/[ETC]ContainerRearrangement.cpp

llddang / 10월 1주차 / 9문제

---

minsuhan1/boj_11660_구간합구하기5.md
minsuhan1/boj_11725_트리의부모찾기.md
minsuhan1/boj_9465_스티커.md

minsuhan1 / 10월 1주차 / 3문제

---

sangbeomheo/BOJ_10828_스택.js
sangbeomheo/BOJ_1874_스택-수열.js
sangbeomheo/BOJ_9012_괄호.js
sangbeomheo/BOJ_9093_단어-뒤집기.js

sangbeomheo / 10월 1주차 / 4문제

---

gusah009/Java/[PGS]섬연결하기.java
gusah009/Java/[PGS]올바른_괄호.java
gusah009/Java/[PGS]카펫.java

gusah009 / 10월 1주차 / 3문제

---

jaewon/party.cpp

[BOJ] 파티 / 골드3 / 1시간  - 플로이드와샬 (최단거리 찾기)
https://www.acmicpc.net/problem/1238

Jaewon / 10월 3주차 /  1문제

---

gusah009/Java/[PGS]NQueen.java
gusah009/Java/[PGS]단속카메라.java
gusah009/Java/[PGS]콜라문제.java
gusah009/[PGS]숫자짝궁.cpp

gusah009 / 10월 4주차 / 4문제

---

namhee/nh099_boj02908.java
namhee/nh100_boj02941.java
namhee/nh101_boj11047.java
namhee/nh102_boj01427.java

프로젝트 일정이 생각보다 힘든....
일주일에 1개씩이라도 풀려고 했고.. 
브론즈로 너무 자주 올리기 좀 그래서 실버만 올립니다😇😇

namhee / 11월 1주차 / 4문제

---

gusah009/Java/[PGS]햄버거만들기.java

gusah009 / 11월 1주차 / 1문제

---

weaver9651/BOJ/BOJ_1260.cpp
weaver9651/BOJ/BOJ_2178.cpp

weaver9651 / 11월 2주차 / 2문제

---

sangbeomheo/PGS_131128_숫자-짝꿍.js
sangbeomheo/PGS_131705_삼총사.js
sangbeomheo/PGS_132267_콜라-문제.js
sangbeomheo/PGS_133499_옹알이-(2).js
sangbeomheo/PGS_133502_햄버거-만들기.js
sangbeomheo/PGS_134240_푸드-파이트-대회.js
sangbeomheo/PGS_17685_[3차] 자동완성.js

SangbeomHeo / 11월 4주차 / 7문제

---

Jeonghak/Programmers/경주로건설.cpp
Jeonghak/Programmers/등산코스정하기.cpp
Jeonghak/Programmers/메뉴리뉴얼.cpp
Jeonghak/Programmers/성격유형검사하기.cpp
Jeonghak/Programmers/셔틀버스.cpp
Jeonghak/Programmers/순위검색.cpp
Jeonghak/Programmers/신규아이디추천.cpp
Jeonghak/Programmers/코딩테스트연습.cpp
Jeonghak/Programmers/파괴되지않은건물.cpp

이전에 push만 해두고 pr을 하지 않은 것들이 있네요...

Jeonghak / 11월 4주차 / 2문제

---

gusah009/Kotlin/[PGS]점찍기.kt
gusah009/Kotlin/[PGS]직사각형별찍기.kt

gusah009 / 12월 1주차 / 2문제

---

thkang727/H_Index.py
thkang727/N개의 최소공배수.py
thkang727/최댓값과 최솟값_.py

취업준비하면서 코딩테스트를 몇번 봤는데, 프로그래머스를 많이 사용하여 저도 맞춰서 프로그래머스에서 하고 있습니다.  LV2가 대략 백준 실버랑 비슷하여 해당 단계로 풀이했습니다. 코딩테스트 전에 파이썬 기본함수 감각 점검을 위해 리스트나 문자열 관련 문제로 풀이했습니다.

thkang727 / 12월 1주차 (11월 3,4주차 포함) / 3문제

---

wi-seong-cheol/BOJ/0x0D Simulation/13335.cpp
wi-seong-cheol/BOJ/0x0D Simulation/14499.cpp
wi-seong-cheol/BOJ/0x10 DP/11053.cpp
wi-seong-cheol/BOJ/0x10 DP/11055.cpp
wi-seong-cheol/BOJ/0x10 DP/11727.cpp
wi-seong-cheol/BOJ/0x10 DP/14501.cpp
wi-seong-cheol/BOJ/0x10 DP/15486.cpp
wi-seong-cheol/BOJ/0x10 DP/1912.cpp
wi-seong-cheol/BOJ/0x10 DP/1932.cpp
wi-seong-cheol/BOJ/0x10 DP/2193.cpp
wi-seong-cheol/BOJ/0x10 DP/9461.cpp

BOJ에서 실버 이상의 DP 문제를 위주로 풀었습니다.

wi-seong-cheol / 12월 2주차 / 11문제

---

lcy8047/10825_국영수.cpp
lcy8047/1916_최소비용구하기.cpp
lcy8047/20551_Sort마스터배지훈의후계자.cpp

lcy8047 / 12월 2주차 / 2문제

---

minsuhan1/boj_10971_외판원순회2.md
minsuhan1/boj_1759_암호만들기.md
minsuhan1/boj_1806_부분합.md
minsuhan1/boj_2512_예산.md

minsuhan1 / 12월 3주차 / 4문제

---

wi-seong-cheol/BOJ/0x03 Array/1475.swift
wi-seong-cheol/BOJ/0x03 Array/3273.swift
wi-seong-cheol/BOJ/0x04 LinkedList/1158.swift
wi-seong-cheol/BOJ/0x04 LinkedList/1406.swift
wi-seong-cheol/BOJ/0x05 Stack I/1874.swift
wi-seong-cheol/BOJ/0x05 Stack I/2493.swift
wi-seong-cheol/BOJ/0x05 Stack I/3015.cpp
wi-seong-cheol/BOJ/0x05 Stack I/3015.swift
wi-seong-cheol/BOJ/0x09 BFS/1012.swift
wi-seong-cheol/BOJ/0x09 BFS/1697.swift
wi-seong-cheol/BOJ/0x10 DP/1003.swift
wi-seong-cheol/BOJ/0x10 DP/10844.cpp
wi-seong-cheol/BOJ/0x10 DP/14002.cpp
wi-seong-cheol/BOJ/0x10 DP/2240.cpp
wi-seong-cheol/PGS/0x06 Queue/두 큐 합 같게 만들기.swift
wi-seong-cheol/wi-seong-cheol.xcodeproj/project.pbxproj

wi-seong-cheol / 12월 3주차 / 14문제

---

Ribo/Tree/BOJ_1967.py
Ribo/Tree/BOJ_2263.py
Ribo/bfs/BOJ_13460.py
Ribo/brute_force/BOJ_1107.py
Ribo/brute_force/BOJ_1476.py
Ribo/brute_force/BOJ_1748.py
Ribo/stack/BOJ_1918.py

저번주 3문제는 완전탐색 위주로 풀었고 이번주 4문제는 자료구조 위주로 풀었습니다.

Ribo / 12월 4주차 / 7문제

---

thkang727/기사단원의 무기.c
thkang727/문자열나누기.c
thkang727/핸드폰 번호 가리기.c

thkang727 / 12월 4주차 / 3문제 

---

Ribo/brute_force/BOJ_12100.py
Ribo/dp/BOJ_14501.py
Ribo/implement/BOJ_13458.py
Ribo/simulation/BOJ_13399.py
Ribo/simulation/BOJ_3190.py

ribo / 12월 5주차 / 5문제 

---

Ribo/brute_force/BOJ_14502.py
Ribo/brute_force/BOJ_14888.py
Ribo/brute_force/BOJ_14889.py
Ribo/implement/BOJ_14890.py
Ribo/implement/BOJ_14891.py

ribo / 1월 1주차 / 5문제

---

shkisme/BOJ/거스름돈14916.java
shkisme/BOJ/나는야포켓몬마스터이다솜.java
shkisme/이코테/게임개발.java
shkisme/이코테/상하좌우.java
shkisme/이코테/숫자카드게임.java
shkisme/이코테/시각.java
shkisme/이코테/왕실의나이트.java
shkisme/이코테/음료수얼려먹기.java
shkisme/이코테/일이될때까지.java
shkisme/이코테/큰수의법칙.java

shkisme / 1월 2주차 / 10문제

---

Ribo/bfs/BOJ_16234.py
Ribo/brute_force/BOJ_15684.py
Ribo/brute_force/BOJ_15686.py
Ribo/implement/BOJ_15685.py

ribo / 1월 2주차 / 4문제

---

c0np4nn4/boj/cpp/1_brz/brz1_1157/alphabet_count.cpp
c0np4nn4/boj/cpp/1_brz/brz1_1546/average.cpp
c0np4nn4/boj/cpp/1_brz/brz2_1152/word_count.cpp
c0np4nn4/boj/cpp/1_brz/brz2_2675/repeating_string.cpp
c0np4nn4/boj/cpp/1_brz/brz3_2562/max.cpp
c0np4nn4/boj/cpp/1_brz/brz5_1008/division.cpp
c0np4nn4/boj/cpp/1_brz/brz5_10952/summation_5.cpp
c0np4nn4/boj/cpp/1_brz/brz5_11654/ascii_code.cpp
c0np4nn4/boj/cpp/1_brz/brz5_1330/comparison.cpp
c0np4nn4/boj/cpp/1_brz/brz5_2438/print_star_1.cpp
c0np4nn4/boj/cpp/1_brz/brz5_2439/print_star_2.cpp
c0np4nn4/boj/cpp/1_brz/brz5_2475/check_number.cpp
c0np4nn4/boj/cpp/1_brz/brz5_2739/mul.cpp
c0np4nn4/boj/cpp/2_slv/slv1_1629/multiplication.cpp
c0np4nn4/boj/cpp/2_slv/slv1_1697/hide_and_seek.cpp
c0np4nn4/boj/cpp/2_slv/slv1_1926/drawing.cpp
c0np4nn4/boj/cpp/2_slv/slv1_2178/maze.cpp
c0np4nn4/boj/cpp/2_slv/slv2_1012/cabbage.cpp
c0np4nn4/boj/cpp/2_slv/slv2_10799/iron_rod.cpp
c0np4nn4/boj/cpp/2_slv/slv4_3986/good_words.cpp
c0np4nn4/boj/cpp/2_slv/slv5_2740/matrix_multiplication.cpp
c0np4nn4/boj/cpp/3_gld/gld4_4179/fire.cpp
c0np4nn4/boj/cpp/3_gld/gld5_10026/color_weakness.cpp
c0np4nn4/boj/cpp/3_gld/gld5_7576/tomato.cpp

BFS 문제와 solved.ac 기준 class 1에 해당하는 문제들을 풀었습니다.

c0np4nn4 / 1월 2주차 / 24문제

---

Ribo/bfs/BOJ_16236.py
Ribo/bfs/BOJ_17144.py
Ribo/implement/BOJ_16235.py

ribo / 1월 3주차 / 3문제

---

c0np4nn4/boj/cpp/2_slv/slv1_2468/safe_zone.cpp
c0np4nn4/boj/cpp/2_slv/slv1_2583/area.cpp
c0np4nn4/boj/cpp/2_slv/slv1_2667/numbering.cpp
c0np4nn4/boj/cpp/2_slv/slv1_5014/start_link.cpp
c0np4nn4/boj/cpp/2_slv/slv1_7562/knight.cpp
c0np4nn4/boj/cpp/2_slv/slv3_1002/turret.cpp
c0np4nn4/boj/cpp/2_slv/slv3_1003/fibonacci.cpp
c0np4nn4/boj/cpp/3_gld/gld3_2206/pathfinding.cpp
c0np4nn4/boj/cpp/3_gld/gld3_9466/term_project.cpp
c0np4nn4/boj/cpp/3_gld/gld4_5427/fire.cpp
c0np4nn4/boj/cpp/3_gld/gld5_6593/building.cpp
c0np4nn4/boj/cpp/3_gld/gld5_7569/tomato.cpp
c0np4nn4/boj/rust/slv3_1003/Cargo.toml
c0np4nn4/boj/rust/slv3_1003/src/main.rs

c0np4nn4 / 1월 3주차 / 12문제

---

c0np4nn4/boj/cpp/2_slv/slv2_1182/partial_number_sequence.cpp
c0np4nn4/boj/cpp/2_slv/slv2_6603/lotto.cpp
c0np4nn4/boj/cpp/2_slv/slv3_15649/n_m_1.cpp
c0np4nn4/boj/cpp/2_slv/slv3_15650/n_m_2.cpp
c0np4nn4/boj/cpp/2_slv/slv3_15651/n_m_3.cpp
c0np4nn4/boj/cpp/2_slv/slv3_15652/n_m_4.cpp
c0np4nn4/boj/cpp/3_gld/gld4_15683/monitoring.cpp
c0np4nn4/boj/cpp/3_gld/gld4_9663/n_queen.cpp

c0np4nn4 / 2월 2주차 / 8문제

---

c0np4nn4/boj/cpp/2_slv/slv3_15654/n_m_5.cpp
c0np4nn4/boj/cpp/2_slv/slv3_15655/n_m_6.cpp

c0np4nn4 / 2월 3주차 / 2문제

---

jokercsi/Programmers/[1차] 뉴스 클러스터링.py
jokercsi/Programmers/프린터.py
jokercsi/Programmers/해시위장.py

https://school.programmers.co.kr/learn/courses/30/lessons/42578

jokercsi / 3월 1주차 / 3문제 

---

shkisme/PGS/Level0/2차원으로 만들기.cpp
shkisme/PGS/Level0/가장 큰 수 찾기.cpp
shkisme/PGS/Level0/다음에 올 숫자.cpp
shkisme/PGS/Level0/문자열 안에 문자열.cpp
shkisme/PGS/Level0/문자열 정렬하기 2.cpp
shkisme/PGS/Level0/배열 뒤집기.cpp
shkisme/PGS/Level0/배열 회전시키기.cpp
shkisme/PGS/Level0/분수의 덧셈.java
shkisme/PGS/Level0/옹알이(1).cpp
shkisme/PGS/Level0/외계 행성의 나이.cpp
shkisme/PGS/Level0/자릿수 더하기.cpp
shkisme/PGS/Level0/최빈값 구하기.cpp
shkisme/PGS/Level0/특정 문자 제거하기.cpp
shkisme/PGS/Level1/숫자문자열과 영단어.cpp
shkisme/이코테/미로탈출.java

프로그래머스 쉬운 문제(Level 0)들 위주로 풀었습니다.
다음 주까지 Level 0 다 풀고 Level 1도 최대한 빨리 다 풀고 싶네요...!

shkisme / 3월 1주차 / 15문제

---

wi-seong-cheol/BOJ/CodingTest/Gold/1062.cpp
wi-seong-cheol/BOJ/CodingTest/Gold/12919.cpp
wi-seong-cheol/BOJ/CodingTest/ReSolve/1149.cpp
wi-seong-cheol/BOJ/CodingTest/ReSolve/1463.cpp
wi-seong-cheol/BOJ/CodingTest/ReSolve/1520.cpp
wi-seong-cheol/BOJ/CodingTest/ReSolve/1699.cpp
wi-seong-cheol/BOJ/CodingTest/ReSolve/1788.cpp
wi-seong-cheol/BOJ/CodingTest/ReSolve/1904.cpp
wi-seong-cheol/BOJ/CodingTest/Silver/1018.cpp
wi-seong-cheol/BOJ/CodingTest/Silver/11723.cpp
wi-seong-cheol/BOJ/CodingTest/Silver/1189.cpp
wi-seong-cheol/BOJ/CodingTest/Silver/1436.cpp
wi-seong-cheol/BOJ/CodingTest/Silver/14620.cpp
wi-seong-cheol/BOJ/CodingTest/Silver/17484.cpp
wi-seong-cheol/BOJ/CodingTest/Silver/2503.cpp
wi-seong-cheol/BOJ/CodingTest/Silver/3085.cpp

wi-seong-cheol / 3월 5주차 / 16문제

---

HayoungNoh/0413_[BOJ] Hello World.cpp
HayoungNoh/0413_[PGS] 두 수의 차.cpp
HayoungNoh/0413_[PGS] 두 수의 합.cpp
HayoungNoh/c++/0413_[BOJ] Hello World

코테 스터디 찾아보다가 깃헙에서 검색하여 들어오게 되었습니다.
이번주는 처음 시작인 기념으로 C++ 입문 관련 간단한 입출력 문제들 풀었습니다.
열심히 하여 챌린지 꼭 달성하고 싶습니다!

Hayoung Noh/4월 2주차/3문제

---

lee-yun-pyo/BOJ/시간 관리하기.js
lee-yun-pyo/BOJ/통나무 건너뛰기.js
lee-yun-pyo/BOJ/팰린드롬 만들기.js

- 알고리즘 분류: **그리디 알고리즘**
- 풀이: 입력값으로 받은 끝내야 하는 시간을 배열로 따로 저장하고 
`hasToEndTimes // [ 5, 14, 16, 20 ]`
시작 시간이 0일 때 끝나는 시간을 따로 배열에 저장한다. 
`endTimes // [ 3, 11, 12, 17 ]`
시간 시간이 1씩 늘어날 때마다 변하는 `endTimes`를 `hasToEndTimes`과 비교해 
같은 인덱스에 `endTimes`가 더 큰 값을 가지고 있으면 reuslt 출력
- 알고리즘 분류: **그리디 알고리즘**
풀이: 답을 도출하는 배열 [2, 5, 9, 7, 4] 이 가장 큰 수를 가운데 놓고 양옆으로 그 다음 큰 수를 
양 옆으로 하나씩 배열된 형태이므로 deque를 사용하여 해결함. 
- 알고리즘 분류: **그리디 알고리즘**
- 풀이: 입력값의 각 문자들의 개수를 구한 후 개수가 홀수인 문자가 2개 이상이면 `"I'm Sorry Hansoo"`를 출력한다.
홀수인 문자가 1개이면 그 홀수 문자를 변수에 따로 저장한다. 
이후 입력값을 정렬한 후 배열 두개를 만들어서 하나는 `push()`함수를 이용하고 다른 하나는 `unshift()`함수를 이용해서 
팰린드롬 형식에 나오게 저장한 후 출력한다.

lee-yun-pyo / 4월 3주차 / 3문제

---

thkang727/15894_수학은 체육과목 입니다.c
thkang727/3036_링.c

C언어 알고리즘 풀이 연습을 위해 다소 난이도를 낮게 하여 준비했습니다.
2문제 모두 일반 구현 + 수학 문제로 풀이했습니다.
1번 문제는 풀이는 매우 쉬웠으나, 변수형태에 따른 표현 범위를 고려하지 못해 조금 시간이 걸렸고,
2번 문제는 단순 연산 표현이 아닌 기약분수 형태 표현이어서 최대공약수를 구하는 함수를 활용하여 풀이했습니다.

thkang727 / 4월5 주차 / 2문제

---

EunjiShin/LeetCode/102.binary-tree-level-order-traversal.java
EunjiShin/LeetCode/121.best-time-to-buy-and-sell-stock.java
EunjiShin/LeetCode/142.linked-list-cycle-ii.java
EunjiShin/LeetCode/278.first-bad-version.java
EunjiShin/LeetCode/409.longest-palindrome.java
EunjiShin/LeetCode/589.n-ary-tree-preorder-traversal.java
EunjiShin/LeetCode/704.binary-search.java
EunjiShin/LeetCode/876.middle-of-the-linked-list.java

https://leetcode.com/study-plan/leetcode-75/?progress=x4qitqxj
리트코드 75문제 챌린지 시작했습니다~~

EunjiShin / 4월 3주차 / 8문제 

---

lee-yun-pyo/BOJ/A와 B.js
lee-yun-pyo/BOJ/IPv6.js
lee-yun-pyo/BOJ/구간 합 구하기 5.js
lee-yun-pyo/BOJ/구간 합 구하기.js
lee-yun-pyo/BOJ/도서관.js
lee-yun-pyo/BOJ/문자열 게임 2.js
lee-yun-pyo/BOJ/볼 모으기.js
lee-yun-pyo/BOJ/블로그.js
lee-yun-pyo/BOJ/빗물.js
lee-yun-pyo/BOJ/수열.js
lee-yun-pyo/BOJ/안정적인 문자열.js
lee-yun-pyo/BOJ/창고 다각형.js
lee-yun-pyo/BOJ/타노스.js

- 알고리즘 분류: **그리디 알고리즘, 구현, 문자열**
- 해결:
T의 마지막 문자가 'A' 이면 마지막 문자를 제외한 T를 다시 T에 저장하고 그렇지 않으면 T 마지막 문자를 제외한 문자에서 이를 역으로 취한 후 T를 저장한다. 이를 반복하고 조건에 맞는 출력을 한다. 
- 알고리즘 분류: **그리디 알고리즘**
- 해결: 
입력값에서 음수 값과 양수 값을 분리하여 따로 배열에 저장하고 이 값들 중 절댓값이 가장 큰 값이 마지막으로 위치하는 좌표이다.
- 알고리즘 분류: **그리디 알고리즘, 스택**
- 알고리즘 분류: **구현**
- 알고리즘 분류: **구현**
풀이: 
1. 4자리 수가 아닌 부분은 0으로 4자리로 채운다.
2. 이후 `::` 이 있다면 `:`을 기준으로 `split(:)` 했을 때 나오는 빈칸의 개수에 따라 결과를 도출한다.  
- 알고리즘 분류: **그리디 알고리즘**
- 풀이: 입력값에서 연속하는 색상의 볼끼리 묶고 묶은 볼들을 이동시킬 때 나오는 최솟값을 구한다.
즉, `RBBBRBRRR` 입력값에서 'R1/B3/R1/B1/R3`으로 묶는다.
- 알고리즘 분류: **문자열, 슬라이딩 윈도우**
- 참고: https://velog.io/@arthur/20437.-%EB%AC%B8%EC%9E%90%EC%97%B4-%EA%B2%8C%EC%9E%84-2-node.js-javascript
- 알고리즘 분류: **자료구조**
- 풀이: 
1. 가장 높은 값 max를 기준으로 max 이전의 기둥과 max이후의 기둥들의 면적을 구한다. 
2. 또한 max가 여러 개 있을 수 있기 때문에 …

lee-yun-pyo / 4월 5주차 ~ 5월 3주차 / 13문제

---

lee-yun-pyo/BOJ/게임.js
lee-yun-pyo/BOJ/과자 나눠주기.js
lee-yun-pyo/BOJ/등수 구하기.js
lee-yun-pyo/BOJ/숫자 카드 2.js
lee-yun-pyo/BOJ/주사위 쌓기.js
lee-yun-pyo/BOJ/탑.js
lee-yun-pyo/BOJ/풍선 맞추기.js

- 알고리즘 분류: **자료 구조, 스택**
- 해결
스택을 생성하여 입력값 순서대로 삽입한다. 
이 때, 삽입 시 입력값과 입력값 순서의 형태로 배열을 구성하여 삽입한다. ex) `stack.push([9, 1])`
만약, 삽입하려는 입력값이 스택의 top보다 크면 
삽입 하려는 값보다 스택의 큰 값이 나올 때까지 작은 값들을 제거(`.pop()`)한다.
이후 스택에 입력값을 삽입하고 삽입한 값이 스택에 있는 값보다 작거나 같으면 스택의 값의 위치를 출력한다. 
삽입하려는 입력값이 스택의 top보다 작거나 같으면, 
스택에 입력값을 삽입하고, 스택의 top 값의 위치 (`stack[index][1]`)을 출력한다. 
- 알고리즘 분류: **구현**
- 풀이
점수가 랭킹 리스트에 올라갈 경우 
입력값 랭킹 리스트에 점수를 삽입하고 이를 비오름차순으로 재정렬한다. 이후 `indexOf(score)` 을 이용하여 삽입한 점수의 index을 구하고 +1을 한다.
- 알고리즘 분류: **해시를 사용한 집합과 맵**
- 풀이:
자료구조 Map을 생성하여 `key`에 카드 숫자를, `value` 에 해당 숫자의 개수를 저장한다. 
이후 Map에 해당 타깃 숫자(`key`)가 없으면 0을, 있으면 해당 `key`에 해당하는 `value` 을 출력한다. 
- 알고리즘 분류: **그리디 알고리즘**
- 풀이: 
빈 배열 `values` 을 생성하고 입력값을 순차적으로 검사해 배열 `values` 에 `입력값 + 1` 이 있다면 그 값을 `입력값`으로 바꾸고 없다면 values에 추가한다. 
이후 `values`의 길이를 …

lee-yun-pyo / 5월 4주차 / 7문제

---

minsuhan1/boj_11501_주식.md
minsuhan1/boj_2477_참외밭.md

minsuhan1 / 5월 4주차 / 2문제

---

minsuhan1/boj_1449_수리공항승.md
minsuhan1/boj_2529_부등호.md

minsuhan1 / 6월 1주차 / 2문제

---

lee-yun-pyo/BOJ/배.js
lee-yun-pyo/BOJ/선분 위의 점.js
lee-yun-pyo/BOJ/소가 길을 건너간 이유 5.js
lee-yun-pyo/BOJ/스택 수열. js
lee-yun-pyo/BOJ/피아노 체조.js

- 알고리즘 분류: **누적합, 슬라이딩 윈도우**
- 풀이: https://velog.io/@lee-yun-pyo/%EC%8A%AC%EB%9D%BC%EC%9D%B4%EB%94%A9-%EC%9C%88%EB%8F%84%EC%9A%B0-SV2-%EC%86%8C%EA%B0%80-%EA%B8%B8%EC%9D%84-%EA%B1%B4%EB%84%88%EA%B0%84-%EC%9D%B4%EC%9C%A0-5
- 알고리즘 분류: **자료구조, 스택**
- 풀이: 스택 배열을 이용
- 알고리즘 분류: **정렬, 이분 탐색**
- 풀이: 입력값 시작점과 끝점을 통해 시작점보다 같거나 큰 값 인덱스를 구하고 끝점보다 같거나 작은 값의 인덱스를 각각 구해서 그 인덱스 사이의 있는 점들의 개수를 구한다. 
- 알고리즘 분류: **누적 합**
- 알고리즘 분류: **그리디**

lee-yun-pyo / 6월 2주차 / 5문제

---

lee-yun-pyo/BOJ/IF문 좀 대신 써줘.js
lee-yun-pyo/BOJ/Maximum Subarray.js
lee-yun-pyo/BOJ/RGB거리.js
lee-yun-pyo/BOJ/가장 긴 증가하는 부분 수열.js
lee-yun-pyo/BOJ/가장 큰 증가하는 부분 수열.js
lee-yun-pyo/BOJ/계단 오르기.js
lee-yun-pyo/BOJ/로프.js
lee-yun-pyo/BOJ/서강근육맨.js
lee-yun-pyo/BOJ/정수 삼각형.js
lee-yun-pyo/BOJ/파도반 수열.js
lee-yun-pyo/BOJ/편의점2.js
lee-yun-pyo/BOJ/흙길 보수하기.js

- 알고리즘 분류: **DP**
- 알고리즘 분류: **DP**
###정수 삼각형 (SV1)
- 알고리즘 분류: **DP** 
- 알고리즘 분류: **DP**
- 알고리즘 분류: **그리디**
- 알고리즘 분류: **수학, 정렬**
- 알고리즘 분류: **DP**
- 알고리즘 분류: **DP, 누적합**
- 알고리즘 분류: **정렬, 스위핑**
- 알고리즘 분류: **이분 탐색**
- 알고리즘 분류: **DP**
- 알고리즘 분류: **그리디, 정렬**

lee-yun-pyo / 6월 4~5주차 / 12문제

---

cocorig/boj_9093.js
cocorig/input.txt

cocorig / 8월 1주차 /  1문제

---

hall_of_fame/jaewon/re1_1074_z.cpp
hall_of_fame/jaewon/re1_1389_bacon.cpp
hall_of_fame/jaewon/re1_1697_play.cpp
hall_of_fame/jaewon/re1_1931_meeting.cpp
hall_of_fame/jaewon/re1_7576_tomato.cpp

Jaewon / 8월 2주차 / 5문제

---

hall_of_fame/jaewon/re1_1620_pokemon.cpp
hall_of_fame/jaewon/re1_2630_colorpapaer.cpp

Jaewon / 8월 3주차 / 2문제

---

splanky0314/Binary_Search/15810_풍선_공장.cpp
splanky0314/Binary_Search/1654_랜선_자르기.cpp
splanky0314/Binary_Search/1920_수_찾기.cpp
splanky0314/Binary_Search/2417_정수_제곱근.cpp
splanky0314/Binary_Search/26258_다중_일차_함수.cpp
splanky0314/Binary_Search/2805_나무_자르기.cpp

splanky0314 / 9월 1주차 / 6문제

---

HamsterStudent/Lv.1_없는_숫자_더하기.js
HamsterStudent/Lv1_문자열을_정수로_바꾸기.js
HamsterStudent/Lv_1_서울에서_김서방_찾기.js

꾸준히 코테 연습해보기 위해 처음으로 참여해봅니다!
잘부탁드립니다.

HamsterStudent / 12월 4주차 / 3문제

---

dj_dong_jae/.gitignore
dj_dong_jae/.idea/aws.xml
dj_dong_jae/.idea/misc.xml
dj_dong_jae/.idea/modules.xml
dj_dong_jae/.idea/vcs.xml
dj_dong_jae/.idea/workspace.xml
dj_dong_jae/dj_dong_jae.iml
dj_dong_jae/src/BOJ_18352/Main.java
dj_dong_jae/src/BOJ_2606/Main.java
dj_dong_jae/src/PGS_60057/Solution.java

- [BOJ] 특정 거리의 도시 찾기 / 실버2 / 30분
- [BOJ] 바이러스 / 실버3 / 30분
- [PGS] 문자열 압축 / Lv.2 / 40분

dj_dong_jae / 1월 1주차 / 3문제

---

kangdy25/BOJ/10101.cpp
kangdy25/BOJ/1085.cpp
kangdy25/BOJ/11653.cpp
kangdy25/BOJ/1193.cpp
kangdy25/BOJ/1978.cpp
kangdy25/BOJ/2501.cpp
kangdy25/BOJ/2581.cpp
kangdy25/BOJ/2869.cpp
kangdy25/BOJ/2903.cpp
kangdy25/BOJ/3009.cpp
kangdy25/BOJ/5086.cpp
kangdy25/BOJ/9506.cpp

단계별로 풀어보기 "일반 수학 1"과 "약수, 배수와 소수" 파트의 문제들을 풀었습니다. (2월 2주차)

kangdy25 / 2월 2, 3주차 / 13문제 

---

kangdy25/BOJ/14215.cpp
kangdy25/BOJ/15894.cpp
kangdy25/BOJ/24262.cpp
kangdy25/BOJ/24263.cpp
kangdy25/BOJ/24264.cpp
kangdy25/BOJ/24265.cpp
kangdy25/BOJ/24266.cpp
kangdy25/BOJ/24267.cpp
kangdy25/BOJ/24313.cpp
kangdy25/BOJ/5073.cpp
kangdy25/BOJ/9063.cpp

"수학은 체육과목입니다" 문제의 코드가 누락되어 다시 올립니다.
단계별로 풀어보기 "기하: 직사각형과 삼각형"과 "시간 복잡도" 파트의 문제들을 풀었습니다. (2월 4, 5주차)

kangdy25 / 2월 4~5주차 / 10문제 

---

kangdy25/BOJ/1018.cpp
kangdy25/BOJ/10989.cpp
kangdy25/BOJ/1436.cpp
kangdy25/BOJ/19532.cpp
kangdy25/BOJ/2231.cpp
kangdy25/BOJ/25305.cpp
kangdy25/BOJ/2587.cpp
kangdy25/BOJ/2750.cpp
kangdy25/BOJ/2751.cpp
kangdy25/BOJ/2798.cpp
kangdy25/BOJ/2839.cpp

단계별로 풀어보기 "브루트 포스"와 "정렬" 파트의 문제들을 풀었습니다. (3월 1, 2주차)

kangdy25 / 3월 1~2주차 / 11문제

---

kangdy25/BOJ/10814.cpp
kangdy25/BOJ/10815.cpp
kangdy25/BOJ/10816.cpp
kangdy25/BOJ/11478.cpp
kangdy25/BOJ/11650.cpp
kangdy25/BOJ/11651.cpp
kangdy25/BOJ/1181.cpp
kangdy25/BOJ/1269.cpp
kangdy25/BOJ/1427.cpp
kangdy25/BOJ/14425.cpp
kangdy25/BOJ/1620.cpp
kangdy25/BOJ/1764.cpp
kangdy25/BOJ/18870.cpp
kangdy25/BOJ/7785.cpp

단계별로 풀어보기 "정렬"과 "집합과 맵" 파트의 문제들을 풀었습니다. (3월 4, 5주차)

kangdy25 / 3월 4~5주차 / 14문제

---

kangdy25/BOJ/13241.cpp
kangdy25/BOJ/13909.cpp
kangdy25/BOJ/17103.cpp
kangdy25/BOJ/1735.cpp
kangdy25/BOJ/1929.cpp
kangdy25/BOJ/1934.cpp
kangdy25/BOJ/2485.cpp
kangdy25/BOJ/4134.cpp
kangdy25/BOJ/4948.cpp

단계별로 풀어보기 "약수, 배수와 소수 2" 파트의 문제들을 풀었습니다. (4월 1, 2주차)

kangdy25 / 4월 1~2주차 / 9문제 
